/* tslint:disable */
/* eslint-disable */
/**
 * DingTalk
 * IntegrationDingTalkOpen Platform<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DingTalkCardData } from './ding-talk-card-data';
import { DingTalkConversationTypeEnum } from './ding-talk-conversation-type-enum';
/**
 * 
 * @export
 * @interface DingTalkSendInteractiveCardsInput
 */
export interface DingTalkSendInteractiveCardsInput {
    /**
     * InteractioncardofinformationTemplateId
     * @type {string}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    cardTemplateId: string;
    /**
     * groupId
     * @type {string}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    openConversationId?: string | null;
    /**
     * ReceiveruserIdList
     * @type {Array<string>}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    receiverUserIdList: Array<string>;
    /**
     * onlyoneSigncardexternalEncoding
     * @type {string}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    outTrackId: string;
    /**
     * of the robotEncoding
     * @type {string}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    robotCode?: string | null;
    /**
     * 
     * @type {DingTalkConversationTypeEnum}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    conversationType: DingTalkConversationTypeEnum;
    /**
     * cardCallbacktimethe routeKey，used forQueryRegisteredcallbackUrl
     * @type {string}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    callbackRouteKey?: string | null;
    /**
     * 
     * @type {DingTalkCardData}
     * @memberof DingTalkSendInteractiveCardsInput
     */
    cardData: DingTalkCardData;
}
