/* tslint:disable */
/* eslint-disable */
/**
 * ApprovalFlow
 * <br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Approval workflow outputParameter
 * @export
 * @interface ApprovalFlowOutput
 */
export interface ApprovalFlowOutput {
    /**
     * Primary keyId
     * @type {number}
     * @memberof ApprovalFlowOutput
     */
    id?: number;
    /**
     * Number
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    code?: string | null;
    /**
     * name
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    name?: string | null;
    /**
     * form
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    formJson?: string | null;
    /**
     * Process
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    flowJson?: string | null;
    /**
     * Remarks
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    remark?: string | null;
    /**
     * Creation Time
     * @type {Date}
     * @memberof ApprovalFlowOutput
     */
    createTime?: Date | null;
    /**
     * Update Time
     * @type {Date}
     * @memberof ApprovalFlowOutput
     */
    updateTime?: Date | null;
    /**
     * CreatorId
     * @type {number}
     * @memberof ApprovalFlowOutput
     */
    createUserId?: number | null;
    /**
     * Creator name
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    createUserName?: string | null;
    /**
     * Modifier ID
     * @type {number}
     * @memberof ApprovalFlowOutput
     */
    updateUserId?: number | null;
    /**
     * Modifier name
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    updateUserName?: string | null;
    /**
     * CreatorDepartmentId
     * @type {number}
     * @memberof ApprovalFlowOutput
     */
    createOrgId?: number | null;
    /**
     * CreatorDepartment namecall
     * @type {string}
     * @memberof ApprovalFlowOutput
     */
    createOrgName?: string | null;
    /**
     * soft delete
     * @type {boolean}
     * @memberof ApprovalFlowOutput
     */
    isDelete?: boolean;
}
