/* tslint:disable */
/* eslint-disable */
/**
 * ApprovalFlow
 * <br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Approval Process Information Form
 * @export
 * @interface ApprovalFlow
 */
export interface ApprovalFlow {
    /**
     * SnowflakeId
     * @type {number}
     * @memberof ApprovalFlow
     */
    id?: number;
    /**
     * Creation Time
     * @type {Date}
     * @memberof ApprovalFlow
     */
    createTime?: Date;
    /**
     * Update Time
     * @type {Date}
     * @memberof ApprovalFlow
     */
    updateTime?: Date | null;
    /**
     * CreatorId
     * @type {number}
     * @memberof ApprovalFlow
     */
    createUserId?: number | null;
    /**
     * Creator name
     * @type {string}
     * @memberof ApprovalFlow
     */
    createUserName?: string | null;
    /**
     * Modifier ID
     * @type {number}
     * @memberof ApprovalFlow
     */
    updateUserId?: number | null;
    /**
     * Modifier name
     * @type {string}
     * @memberof ApprovalFlow
     */
    updateUserName?: string | null;
    /**
     * soft delete
     * @type {boolean}
     * @memberof ApprovalFlow
     */
    isDelete?: boolean;
    /**
     * CreatorDepartmentId
     * @type {number}
     * @memberof ApprovalFlow
     */
    createOrgId?: number | null;
    /**
     * CreatorDepartment namecall
     * @type {string}
     * @memberof ApprovalFlow
     */
    createOrgName?: string | null;
    /**
     * Number
     * @type {string}
     * @memberof ApprovalFlow
     */
    code?: string | null;
    /**
     * name
     * @type {string}
     * @memberof ApprovalFlow
     */
    name?: string | null;
    /**
     * form
     * @type {string}
     * @memberof ApprovalFlow
     */
    formJson?: string | null;
    /**
     * Process
     * @type {string}
     * @memberof ApprovalFlow
     */
    flowJson?: string | null;
    /**
     * state
     * @type {number}
     * @memberof ApprovalFlow
     */
    status?: number | null;
    /**
     * Remarks
     * @type {string}
     * @memberof ApprovalFlow
     */
    remark?: string | null;
}
