/* tslint:disable */
/* eslint-disable */
/**
 * ApprovalFlow
 * <br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Approval workflowUpdateInputParameter
 * @export
 * @interface UpdateApprovalFlowInput
 */
export interface UpdateApprovalFlowInput {
    /**
     * Creation Time
     * @type {Date}
     * @memberof UpdateApprovalFlowInput
     */
    createTime?: Date;
    /**
     * Update Time
     * @type {Date}
     * @memberof UpdateApprovalFlowInput
     */
    updateTime?: Date | null;
    /**
     * CreatorId
     * @type {number}
     * @memberof UpdateApprovalFlowInput
     */
    createUserId?: number | null;
    /**
     * Creator name
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    createUserName?: string | null;
    /**
     * Modifier ID
     * @type {number}
     * @memberof UpdateApprovalFlowInput
     */
    updateUserId?: number | null;
    /**
     * Modifier name
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    updateUserName?: string | null;
    /**
     * soft delete
     * @type {boolean}
     * @memberof UpdateApprovalFlowInput
     */
    isDelete?: boolean;
    /**
     * CreatorDepartmentId
     * @type {number}
     * @memberof UpdateApprovalFlowInput
     */
    createOrgId?: number | null;
    /**
     * CreatorDepartment namecall
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    createOrgName?: string | null;
    /**
     * Number
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    code?: string | null;
    /**
     * name
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    name?: string | null;
    /**
     * form
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    formJson?: string | null;
    /**
     * Process
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    flowJson?: string | null;
    /**
     * state
     * @type {number}
     * @memberof UpdateApprovalFlowInput
     */
    status?: number | null;
    /**
     * Remarks
     * @type {string}
     * @memberof UpdateApprovalFlowInput
     */
    remark?: string | null;
    /**
     * Primary keyId
     * @type {number}
     * @memberof UpdateApprovalFlowInput
     */
    id: number;
}
