/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultListCodeGenConfig } from '../models';
import { AdminResultSysCodeGenConfig } from '../models';
import { CodeGenConfig } from '../models';
/**
 * SysCodeGenConfigApi - axios parameter creator
 * @export
 */
export const SysCodeGenConfigApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get code generation configuration details 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysCodeGenConfigDetailGet: async (id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysCodeGenConfig/detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            if (codeGenId !== undefined) {
                localVarQueryParameter['CodeGenId'] = codeGenId;
            }

            if (columnName !== undefined) {
                localVarQueryParameter['ColumnName'] = columnName;
            }

            if (columnKey !== undefined) {
                localVarQueryParameter['ColumnKey'] = columnKey;
            }

            if (propertyName !== undefined) {
                localVarQueryParameter['PropertyName'] = propertyName;
            }

            if (columnLength !== undefined) {
                localVarQueryParameter['ColumnLength'] = columnLength;
            }

            if (lowerPropertyName !== undefined) {
                localVarQueryParameter['LowerPropertyName'] = lowerPropertyName;
            }

            if (columnComment !== undefined) {
                localVarQueryParameter['ColumnComment'] = columnComment;
            }

            if (netType !== undefined) {
                localVarQueryParameter['NetType'] = netType;
            }

            if (dataType !== undefined) {
                localVarQueryParameter['DataType'] = dataType;
            }

            if (defaultValue !== undefined) {
                localVarQueryParameter['DefaultValue'] = defaultValue;
            }

            if (nullableNetType !== undefined) {
                localVarQueryParameter['NullableNetType'] = nullableNetType;
            }

            if (effectType !== undefined) {
                localVarQueryParameter['EffectType'] = effectType;
            }

            if (fkConfigId !== undefined) {
                localVarQueryParameter['FkConfigId'] = fkConfigId;
            }

            if (fkEntityName !== undefined) {
                localVarQueryParameter['FkEntityName'] = fkEntityName;
            }

            if (fkTableName !== undefined) {
                localVarQueryParameter['FkTableName'] = fkTableName;
            }

            if (lowerFkEntityName !== undefined) {
                localVarQueryParameter['LowerFkEntityName'] = lowerFkEntityName;
            }

            if (fkLinkColumnName !== undefined) {
                localVarQueryParameter['FkLinkColumnName'] = fkLinkColumnName;
            }

            if (fkDisplayColumns !== undefined) {
                localVarQueryParameter['FkDisplayColumns'] = fkDisplayColumns;
            }

            if (fkDisplayColumnList) {
                localVarQueryParameter['FkDisplayColumnList'] = fkDisplayColumnList;
            }

            if (lowerFkDisplayColumnsList) {
                localVarQueryParameter['LowerFkDisplayColumnsList'] = lowerFkDisplayColumnsList;
            }

            if (fkColumnNetType !== undefined) {
                localVarQueryParameter['FkColumnNetType'] = fkColumnNetType;
            }

            if (pidColumn !== undefined) {
                localVarQueryParameter['PidColumn'] = pidColumn;
            }

            if (dictTypeCode !== undefined) {
                localVarQueryParameter['DictTypeCode'] = dictTypeCode;
            }

            if (queryType !== undefined) {
                localVarQueryParameter['QueryType'] = queryType;
            }

            if (whetherQuery !== undefined) {
                localVarQueryParameter['WhetherQuery'] = whetherQuery;
            }

            if (whetherRetract !== undefined) {
                localVarQueryParameter['WhetherRetract'] = whetherRetract;
            }

            if (whetherRequired !== undefined) {
                localVarQueryParameter['WhetherRequired'] = whetherRequired;
            }

            if (whetherSortable !== undefined) {
                localVarQueryParameter['WhetherSortable'] = whetherSortable;
            }

            if (whetherTable !== undefined) {
                localVarQueryParameter['WhetherTable'] = whetherTable;
            }

            if (whetherAddUpdate !== undefined) {
                localVarQueryParameter['WhetherAddUpdate'] = whetherAddUpdate;
            }

            if (whetherImport !== undefined) {
                localVarQueryParameter['WhetherImport'] = whetherImport;
            }

            if (whetherCommon !== undefined) {
                localVarQueryParameter['WhetherCommon'] = whetherCommon;
            }

            if (orderNo !== undefined) {
                localVarQueryParameter['OrderNo'] = orderNo;
            }

            if (isSelectorEffectType !== undefined) {
                localVarQueryParameter['IsSelectorEffectType'] = isSelectorEffectType;
            }

            if (propertyNameTrimEndId !== undefined) {
                localVarQueryParameter['PropertyNameTrimEndId'] = propertyNameTrimEndId;
            }

            if (lowerPropertyNameTrimEndId !== undefined) {
                localVarQueryParameter['LowerPropertyNameTrimEndId'] = lowerPropertyNameTrimEndId;
            }

            if (extendedPropertyName !== undefined) {
                localVarQueryParameter['ExtendedPropertyName'] = extendedPropertyName;
            }

            if (lowerExtendedPropertyName !== undefined) {
                localVarQueryParameter['LowerExtendedPropertyName'] = lowerExtendedPropertyName;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of code generation configurations 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysCodeGenConfigListGet: async (id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysCodeGenConfig/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            if (codeGenId !== undefined) {
                localVarQueryParameter['CodeGenId'] = codeGenId;
            }

            if (columnName !== undefined) {
                localVarQueryParameter['ColumnName'] = columnName;
            }

            if (columnKey !== undefined) {
                localVarQueryParameter['ColumnKey'] = columnKey;
            }

            if (propertyName !== undefined) {
                localVarQueryParameter['PropertyName'] = propertyName;
            }

            if (columnLength !== undefined) {
                localVarQueryParameter['ColumnLength'] = columnLength;
            }

            if (lowerPropertyName !== undefined) {
                localVarQueryParameter['LowerPropertyName'] = lowerPropertyName;
            }

            if (columnComment !== undefined) {
                localVarQueryParameter['ColumnComment'] = columnComment;
            }

            if (netType !== undefined) {
                localVarQueryParameter['NetType'] = netType;
            }

            if (dataType !== undefined) {
                localVarQueryParameter['DataType'] = dataType;
            }

            if (defaultValue !== undefined) {
                localVarQueryParameter['DefaultValue'] = defaultValue;
            }

            if (nullableNetType !== undefined) {
                localVarQueryParameter['NullableNetType'] = nullableNetType;
            }

            if (effectType !== undefined) {
                localVarQueryParameter['EffectType'] = effectType;
            }

            if (fkConfigId !== undefined) {
                localVarQueryParameter['FkConfigId'] = fkConfigId;
            }

            if (fkEntityName !== undefined) {
                localVarQueryParameter['FkEntityName'] = fkEntityName;
            }

            if (fkTableName !== undefined) {
                localVarQueryParameter['FkTableName'] = fkTableName;
            }

            if (lowerFkEntityName !== undefined) {
                localVarQueryParameter['LowerFkEntityName'] = lowerFkEntityName;
            }

            if (fkLinkColumnName !== undefined) {
                localVarQueryParameter['FkLinkColumnName'] = fkLinkColumnName;
            }

            if (fkDisplayColumns !== undefined) {
                localVarQueryParameter['FkDisplayColumns'] = fkDisplayColumns;
            }

            if (fkDisplayColumnList) {
                localVarQueryParameter['FkDisplayColumnList'] = fkDisplayColumnList;
            }

            if (lowerFkDisplayColumnsList) {
                localVarQueryParameter['LowerFkDisplayColumnsList'] = lowerFkDisplayColumnsList;
            }

            if (fkColumnNetType !== undefined) {
                localVarQueryParameter['FkColumnNetType'] = fkColumnNetType;
            }

            if (pidColumn !== undefined) {
                localVarQueryParameter['PidColumn'] = pidColumn;
            }

            if (dictTypeCode !== undefined) {
                localVarQueryParameter['DictTypeCode'] = dictTypeCode;
            }

            if (queryType !== undefined) {
                localVarQueryParameter['QueryType'] = queryType;
            }

            if (whetherQuery !== undefined) {
                localVarQueryParameter['WhetherQuery'] = whetherQuery;
            }

            if (whetherRetract !== undefined) {
                localVarQueryParameter['WhetherRetract'] = whetherRetract;
            }

            if (whetherRequired !== undefined) {
                localVarQueryParameter['WhetherRequired'] = whetherRequired;
            }

            if (whetherSortable !== undefined) {
                localVarQueryParameter['WhetherSortable'] = whetherSortable;
            }

            if (whetherTable !== undefined) {
                localVarQueryParameter['WhetherTable'] = whetherTable;
            }

            if (whetherAddUpdate !== undefined) {
                localVarQueryParameter['WhetherAddUpdate'] = whetherAddUpdate;
            }

            if (whetherImport !== undefined) {
                localVarQueryParameter['WhetherImport'] = whetherImport;
            }

            if (whetherCommon !== undefined) {
                localVarQueryParameter['WhetherCommon'] = whetherCommon;
            }

            if (orderNo !== undefined) {
                localVarQueryParameter['OrderNo'] = orderNo;
            }

            if (isSelectorEffectType !== undefined) {
                localVarQueryParameter['IsSelectorEffectType'] = isSelectorEffectType;
            }

            if (propertyNameTrimEndId !== undefined) {
                localVarQueryParameter['PropertyNameTrimEndId'] = propertyNameTrimEndId;
            }

            if (lowerPropertyNameTrimEndId !== undefined) {
                localVarQueryParameter['LowerPropertyNameTrimEndId'] = lowerPropertyNameTrimEndId;
            }

            if (extendedPropertyName !== undefined) {
                localVarQueryParameter['ExtendedPropertyName'] = extendedPropertyName;
            }

            if (lowerExtendedPropertyName !== undefined) {
                localVarQueryParameter['LowerExtendedPropertyName'] = lowerExtendedPropertyName;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update code generation configuration 🔖
         * @param {Array<CodeGenConfig>} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysCodeGenConfigUpdatePost: async (body?: Array<CodeGenConfig>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysCodeGenConfig/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysCodeGenConfigApi - functional programming interface
 * @export
 */
export const SysCodeGenConfigApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get code generation configuration details 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigDetailGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultSysCodeGenConfig>>> {
            const localVarAxiosArgs = await SysCodeGenConfigApiAxiosParamCreator(configuration).apiSysCodeGenConfigDetailGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a list of code generation configurations 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigListGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultListCodeGenConfig>>> {
            const localVarAxiosArgs = await SysCodeGenConfigApiAxiosParamCreator(configuration).apiSysCodeGenConfigListGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update code generation configuration 🔖
         * @param {Array<CodeGenConfig>} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigUpdatePost(body?: Array<CodeGenConfig>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SysCodeGenConfigApiAxiosParamCreator(configuration).apiSysCodeGenConfigUpdatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysCodeGenConfigApi - factory interface
 * @export
 */
export const SysCodeGenConfigApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get code generation configuration details 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigDetailGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultSysCodeGenConfig>> {
            return SysCodeGenConfigApiFp(configuration).apiSysCodeGenConfigDetailGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of code generation configurations 🔖
         * @param {number} [id] Primary keyId
         * @param {number} [codeGenId] code generationMain TableID
         * @param {string} [columnName] DataWarehouseField Name
         * @param {string} [columnKey] Masterforeign key
         * @param {string} [propertyName] Entity attributeName
         * @param {number} [columnLength] Field data length
         * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
         * @param {string} [columnComment] FieldDescription
         * @param {string} [netType] .NETType
         * @param {string} [dataType] DataWarehouseinType（PhysicsType）
         * @param {string} [defaultValue] FieldDataDefault value
         * @param {string} [nullableNetType] Nullable.NETType
         * @param {string} [effectType] Type of effect（dictionary）
         * @param {string} [fkConfigId] Foreign key library identifier
         * @param {string} [fkEntityName] Foreign key entity name
         * @param {string} [fkTableName] Foreign key table name
         * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
         * @param {string} [fkLinkColumnName] Foreign key link field
         * @param {string} [fkDisplayColumns] Foreign key display field
         * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
         * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
         * @param {string} [fkColumnNetType] Foreign key display field .NET type
         * @param {string} [pidColumn] Parent field
         * @param {string} [dictTypeCode] dictionarycode
         * @param {string} [queryType] Query method
         * @param {string} [whetherQuery] Is it a query condition?
         * @param {string} [whetherRetract] Whether the list is indented（dictionary）
         * @param {string} [whetherRequired] Is it required?（dictionary）
         * @param {string} [whetherSortable] Is it sortable?（dictionary）
         * @param {string} [whetherTable] List Display
         * @param {string} [whetherAddUpdate] Additions and changes
         * @param {string} [whetherImport] import
         * @param {string} [whetherCommon] YesnoYesGeneralField
         * @param {number} [orderNo] Sort
         * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
         * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
         * @param {string} [extendedPropertyName] ExpandAttributename
         * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigListGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultListCodeGenConfig>> {
            return SysCodeGenConfigApiFp(configuration).apiSysCodeGenConfigListGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update code generation configuration 🔖
         * @param {Array<CodeGenConfig>} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysCodeGenConfigUpdatePost(body?: Array<CodeGenConfig>, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SysCodeGenConfigApiFp(configuration).apiSysCodeGenConfigUpdatePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysCodeGenConfigApi - object-oriented interface
 * @export
 * @class SysCodeGenConfigApi
 * @extends {BaseAPI}
 */
export class SysCodeGenConfigApi extends BaseAPI {
    /**
     * 
     * @summary Get code generation configuration details 🔖
     * @param {number} [id] Primary keyId
     * @param {number} [codeGenId] code generationMain TableID
     * @param {string} [columnName] DataWarehouseField Name
     * @param {string} [columnKey] Masterforeign key
     * @param {string} [propertyName] Entity attributeName
     * @param {number} [columnLength] Field data length
     * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
     * @param {string} [columnComment] FieldDescription
     * @param {string} [netType] .NETType
     * @param {string} [dataType] DataWarehouseinType（PhysicsType）
     * @param {string} [defaultValue] FieldDataDefault value
     * @param {string} [nullableNetType] Nullable.NETType
     * @param {string} [effectType] Type of effect（dictionary）
     * @param {string} [fkConfigId] Foreign key library identifier
     * @param {string} [fkEntityName] Foreign key entity name
     * @param {string} [fkTableName] Foreign key table name
     * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
     * @param {string} [fkLinkColumnName] Foreign key link field
     * @param {string} [fkDisplayColumns] Foreign key display field
     * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
     * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
     * @param {string} [fkColumnNetType] Foreign key display field .NET type
     * @param {string} [pidColumn] Parent field
     * @param {string} [dictTypeCode] dictionarycode
     * @param {string} [queryType] Query method
     * @param {string} [whetherQuery] Is it a query condition?
     * @param {string} [whetherRetract] Whether the list is indented（dictionary）
     * @param {string} [whetherRequired] Is it required?（dictionary）
     * @param {string} [whetherSortable] Is it sortable?（dictionary）
     * @param {string} [whetherTable] List Display
     * @param {string} [whetherAddUpdate] Additions and changes
     * @param {string} [whetherImport] import
     * @param {string} [whetherCommon] YesnoYesGeneralField
     * @param {number} [orderNo] Sort
     * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
     * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
     * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
     * @param {string} [extendedPropertyName] ExpandAttributename
     * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysCodeGenConfigApi
     */
    public async apiSysCodeGenConfigDetailGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultSysCodeGenConfig>> {
        return SysCodeGenConfigApiFp(this.configuration).apiSysCodeGenConfigDetailGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a list of code generation configurations 🔖
     * @param {number} [id] Primary keyId
     * @param {number} [codeGenId] code generationMain TableID
     * @param {string} [columnName] DataWarehouseField Name
     * @param {string} [columnKey] Masterforeign key
     * @param {string} [propertyName] Entity attributeName
     * @param {number} [columnLength] Field data length
     * @param {string} [lowerPropertyName] DataWarehouseField Name(lowercase first letter)
     * @param {string} [columnComment] FieldDescription
     * @param {string} [netType] .NETType
     * @param {string} [dataType] DataWarehouseinType（PhysicsType）
     * @param {string} [defaultValue] FieldDataDefault value
     * @param {string} [nullableNetType] Nullable.NETType
     * @param {string} [effectType] Type of effect（dictionary）
     * @param {string} [fkConfigId] Foreign key library identifier
     * @param {string} [fkEntityName] Foreign key entity name
     * @param {string} [fkTableName] Foreign key table name
     * @param {string} [lowerFkEntityName] Foreign key entity name(lowercase first letter)
     * @param {string} [fkLinkColumnName] Foreign key link field
     * @param {string} [fkDisplayColumns] Foreign key display field
     * @param {Array<string>} [fkDisplayColumnList] Foreign key display field
     * @param {Array<string>} [lowerFkDisplayColumnsList] Foreign key display field(lowercase first letter)
     * @param {string} [fkColumnNetType] Foreign key display field .NET type
     * @param {string} [pidColumn] Parent field
     * @param {string} [dictTypeCode] dictionarycode
     * @param {string} [queryType] Query method
     * @param {string} [whetherQuery] Is it a query condition?
     * @param {string} [whetherRetract] Whether the list is indented（dictionary）
     * @param {string} [whetherRequired] Is it required?（dictionary）
     * @param {string} [whetherSortable] Is it sortable?（dictionary）
     * @param {string} [whetherTable] List Display
     * @param {string} [whetherAddUpdate] Additions and changes
     * @param {string} [whetherImport] import
     * @param {string} [whetherCommon] YesnoYesGeneralField
     * @param {number} [orderNo] Sort
     * @param {boolean} [isSelectorEffectType] YesnoYesSelector control
     * @param {string} [propertyNameTrimEndId] Remove the tailIdofAttributeName
     * @param {string} [lowerPropertyNameTrimEndId] Remove the tailIdofAttributeName
     * @param {string} [extendedPropertyName] ExpandAttributename
     * @param {string} [lowerExtendedPropertyName] Extension with lowercase initialAttributename
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysCodeGenConfigApi
     */
    public async apiSysCodeGenConfigListGet(id?: number, codeGenId?: number, columnName?: string, columnKey?: string, propertyName?: string, columnLength?: number, lowerPropertyName?: string, columnComment?: string, netType?: string, dataType?: string, defaultValue?: string, nullableNetType?: string, effectType?: string, fkConfigId?: string, fkEntityName?: string, fkTableName?: string, lowerFkEntityName?: string, fkLinkColumnName?: string, fkDisplayColumns?: string, fkDisplayColumnList?: Array<string>, lowerFkDisplayColumnsList?: Array<string>, fkColumnNetType?: string, pidColumn?: string, dictTypeCode?: string, queryType?: string, whetherQuery?: string, whetherRetract?: string, whetherRequired?: string, whetherSortable?: string, whetherTable?: string, whetherAddUpdate?: string, whetherImport?: string, whetherCommon?: string, orderNo?: number, isSelectorEffectType?: boolean, propertyNameTrimEndId?: string, lowerPropertyNameTrimEndId?: string, extendedPropertyName?: string, lowerExtendedPropertyName?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultListCodeGenConfig>> {
        return SysCodeGenConfigApiFp(this.configuration).apiSysCodeGenConfigListGet(id, codeGenId, columnName, columnKey, propertyName, columnLength, lowerPropertyName, columnComment, netType, dataType, defaultValue, nullableNetType, effectType, fkConfigId, fkEntityName, fkTableName, lowerFkEntityName, fkLinkColumnName, fkDisplayColumns, fkDisplayColumnList, lowerFkDisplayColumnsList, fkColumnNetType, pidColumn, dictTypeCode, queryType, whetherQuery, whetherRetract, whetherRequired, whetherSortable, whetherTable, whetherAddUpdate, whetherImport, whetherCommon, orderNo, isSelectorEffectType, propertyNameTrimEndId, lowerPropertyNameTrimEndId, extendedPropertyName, lowerExtendedPropertyName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update code generation configuration 🔖
     * @param {Array<CodeGenConfig>} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysCodeGenConfigApi
     */
    public async apiSysCodeGenConfigUpdatePost(body?: Array<CodeGenConfig>, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SysCodeGenConfigApiFp(this.configuration).apiSysCodeGenConfigUpdatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
