/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultDataSet } from '../models';
import { AdminResultDataTable } from '../models';
import { AdminResultIActionResult } from '../models';
import { BaseProcInput } from '../models';
import { ExportProcByTMPInput } from '../models';
import { ExportProcInput } from '../models';
/**
 * SysProcApi - axios parameter creator
 * @export
 */
export const SysProcApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ObtainStored procedure returnDatacollection-Oracle、DamengParameterThe order cannot be wrong  Oracle Returntable、table1，OtherReturntable1、table2。Applicable to reports、Complex detailed pages, etc. 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysProcCommonDataSetPost: async (body?: BaseProcInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysProc/commonDataSet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ExportStored procedureData-Specified column，Not specifiedFieldwill behide 🔖
         * @param {ExportProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysProcPocExport2Post: async (body?: ExportProcInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysProc/pocExport2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary According toTemplateExportStored procedureData 🔖
         * @param {ExportProcByTMPInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysProcPocExportPost: async (body?: ExportProcByTMPInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysProc/pocExport`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ObtainStored procedure returns a table-Oracle、DamengParameterThe order cannot be wrong 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSysProcProcTablePost: async (body?: BaseProcInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sysProc/procTable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SysProcApi - functional programming interface
 * @export
 */
export const SysProcApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ObtainStored procedure returnDatacollection-Oracle、DamengParameterThe order cannot be wrong  Oracle Returntable、table1，OtherReturntable1、table2。Applicable to reports、Complex detailed pages, etc. 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcCommonDataSetPost(body?: BaseProcInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultDataSet>>> {
            const localVarAxiosArgs = await SysProcApiAxiosParamCreator(configuration).apiSysProcCommonDataSetPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary ExportStored procedureData-Specified column，Not specifiedFieldwill behide 🔖
         * @param {ExportProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcPocExport2Post(body?: ExportProcInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultIActionResult>>> {
            const localVarAxiosArgs = await SysProcApiAxiosParamCreator(configuration).apiSysProcPocExport2Post(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary According toTemplateExportStored procedureData 🔖
         * @param {ExportProcByTMPInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcPocExportPost(body?: ExportProcByTMPInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultIActionResult>>> {
            const localVarAxiosArgs = await SysProcApiAxiosParamCreator(configuration).apiSysProcPocExportPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary ObtainStored procedure returns a table-Oracle、DamengParameterThe order cannot be wrong 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcProcTablePost(body?: BaseProcInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultDataTable>>> {
            const localVarAxiosArgs = await SysProcApiAxiosParamCreator(configuration).apiSysProcProcTablePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SysProcApi - factory interface
 * @export
 */
export const SysProcApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary ObtainStored procedure returnDatacollection-Oracle、DamengParameterThe order cannot be wrong  Oracle Returntable、table1，OtherReturntable1、table2。Applicable to reports、Complex detailed pages, etc. 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcCommonDataSetPost(body?: BaseProcInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultDataSet>> {
            return SysProcApiFp(configuration).apiSysProcCommonDataSetPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ExportStored procedureData-Specified column，Not specifiedFieldwill behide 🔖
         * @param {ExportProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcPocExport2Post(body?: ExportProcInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultIActionResult>> {
            return SysProcApiFp(configuration).apiSysProcPocExport2Post(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary According toTemplateExportStored procedureData 🔖
         * @param {ExportProcByTMPInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcPocExportPost(body?: ExportProcByTMPInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultIActionResult>> {
            return SysProcApiFp(configuration).apiSysProcPocExportPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ObtainStored procedure returns a table-Oracle、DamengParameterThe order cannot be wrong 🔖
         * @param {BaseProcInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSysProcProcTablePost(body?: BaseProcInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultDataTable>> {
            return SysProcApiFp(configuration).apiSysProcProcTablePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SysProcApi - object-oriented interface
 * @export
 * @class SysProcApi
 * @extends {BaseAPI}
 */
export class SysProcApi extends BaseAPI {
    /**
     * 
     * @summary ObtainStored procedure returnDatacollection-Oracle、DamengParameterThe order cannot be wrong  Oracle Returntable、table1，OtherReturntable1、table2。Applicable to reports、Complex detailed pages, etc. 🔖
     * @param {BaseProcInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysProcApi
     */
    public async apiSysProcCommonDataSetPost(body?: BaseProcInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultDataSet>> {
        return SysProcApiFp(this.configuration).apiSysProcCommonDataSetPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary ExportStored procedureData-Specified column，Not specifiedFieldwill behide 🔖
     * @param {ExportProcInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysProcApi
     */
    public async apiSysProcPocExport2Post(body?: ExportProcInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultIActionResult>> {
        return SysProcApiFp(this.configuration).apiSysProcPocExport2Post(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary According toTemplateExportStored procedureData 🔖
     * @param {ExportProcByTMPInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysProcApi
     */
    public async apiSysProcPocExportPost(body?: ExportProcByTMPInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultIActionResult>> {
        return SysProcApiFp(this.configuration).apiSysProcPocExportPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary ObtainStored procedure returns a table-Oracle、DamengParameterThe order cannot be wrong 🔖
     * @param {BaseProcInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SysProcApi
     */
    public async apiSysProcProcTablePost(body?: BaseProcInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultDataTable>> {
        return SysProcApiFp(this.configuration).apiSysProcProcTablePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
