/* tslint:disable */
/* eslint-disable */
/**
 * DingTalkOpen Platform
 * IntegrationDingTalkOpen Platform<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Approver } from './approver';
import { FormComponentValue } from './form-component-value';
import { TargetSelectActioner } from './target-select-actioner';
 /**
 * 
 *
 * @export
 * @interface DingTalkWorkflowProcessInstancesInput
 */
export interface DingTalkWorkflowProcessInstancesInput {

    /**
     * FounderUser ID
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    originatorUserId?: string | null;

    /**
     * ApprovalTemplateofProcessEncoding
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    processCode?: string | null;

    /**
     * DepartmentID
     *
     * @type {number}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    deptId?: number;

    /**
     * Micro-applicationAgentId
     *
     * @type {number}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    microappAgentId?: number;

    /**
     * List of approvers（Supports multiple nodes）
     *
     * @type {Array<Approver>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    approvers?: Array<Approver> | null;

    /**
     * CC List
     *
     * @type {Array<string>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    ccList?: Array<string> | null;

    /**
     * CC Location：START（Start），MIDDLE（inspace），END（end）
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    ccPosition?: string | null;

    /**
     * Dynamically select the handler for the target（For scenarios such as joint signing or multiple approvals）
     *
     * @type {Array<TargetSelectActioner>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    targetSelectActioners?: Array<TargetSelectActioner> | null;

    /**
     * formgrouppiecevalueList
     *
     * @type {Array<FormComponentValue>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    formComponentValues?: Array<FormComponentValue> | null;

    /**
     * RequestID，Used for idempotency control
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    requestId?: string | null;
}
