/* tslint:disable */
/* eslint-disable */
/**
 * DingTalkOpen Platform
 * IntegrationDingTalkOpen Platform<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * formgrouppiecevalue
 *
 * @export
 * @interface FormComponentValue
 */
export interface FormComponentValue {

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    componentType?: string | null;

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    bizAlias?: string | null;

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    value?: string | null;

    /**
     * @type {string}
     * @memberof FormComponentValue
     */
    extValue?: string | null;
}
