/* tslint:disable */
/* eslint-disable */
/**
 * DingTalkOpen Platform
 * IntegrationDingTalkOpen Platform<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Dynamically select the handler
 *
 * @export
 * @interface TargetSelectActioner
 */
export interface TargetSelectActioner {

    /**
     * HandlerKey，correspondingforminthe personnel selection controlkey
     *
     * @type {string}
     * @memberof TargetSelectActioner
     */
    actionerKey?: string | null;

    /**
     * This control optioninofUser IDList
     *
     * @type {Array<string>}
     * @memberof TargetSelectActioner
     */
    actionerUserIds?: Array<string> | null;
}
