/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
import { TableUniqueConfigItem } from './table-unique-config-item';
 /**
 * 
 *
 * @export
 * @interface AddCodeGenInput
 */
export interface AddCodeGenInput {

    /**
     * @type {Search}
     * @memberof AddCodeGenInput
     */
    search?: Search;

    /**
     * BlurryQueryKeywords
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof AddCodeGenInput
     */
    filter?: Filter;

    /**
     * Current page number
     *
     * @type {number}
     * @memberof AddCodeGenInput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof AddCodeGenInput
     */
    pageSize?: number;

    /**
     * SortField
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    field?: string | null;

    /**
     * SortDirection
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    order?: string | null;

    /**
     * Descending orderSort
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    descStr?: string | null;

    /**
     * Class name
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    className?: string | null;

    /**
     * Whether to remove the table prefix
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    tablePrefix?: string | null;

    /**
     * Library Locator Name
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    configId?: string | null;

    /**
     * DataLibrary name(ReserveField)
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    dbName?: string | null;

    /**
     * Database type
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    dbType?: string | null;

    /**
     * Database link
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    connectionString?: string | null;

    /**
     * Function Name（Database table namecall）
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    tableComment?: string | null;

    /**
     * table onlyoneFieldList
     *
     * @type {Array<TableUniqueConfigItem>}
     * @memberof AddCodeGenInput
     */
    tableUniqueList?: Array<TableUniqueConfigItem> | null;

    /**
     * menuApplicationpointsClass（ApplicationEncoding）
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    menuApplication?: string | null;

    /**
     * menuParent
     *
     * @type {number}
     * @memberof AddCodeGenInput
     */
    menuPid?: number | null;

    /**
     * Menu icon
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    menuIcon?: string | null;

    /**
     * Page directory
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    pagePath?: string | null;

    /**
     * Supported print types
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    printType?: string | null;

    /**
     * Print Template Name
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    printName?: string | null;

    /**
     * Database table name
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    tableName: string;

    /**
     * Business Name（Business code packagename）
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    busName: string;

    /**
     * namespace
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    nameSpace: string;

    /**
     * Author's Name
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    authorName: string;

    /**
     * Generation method
     *
     * @type {string}
     * @memberof AddCodeGenInput
     */
    generateType: string;

    /**
     * Generate menu?
     *
     * @type {boolean}
     * @memberof AddCodeGenInput
     */
    generateMenu: boolean;
}
