/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DbType } from './db-type';
import { StatusEnum } from './status-enum';
import { TenantTypeEnum } from './tenant-type-enum';
import { YesNoEnum } from './yes-no-enum';
 /**
 * 
 *
 * @export
 * @interface AddTenantInput
 */
export interface AddTenantInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof AddTenantInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof AddTenantInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    updateUserName?: string | null;

    /**
     * Rent-controlled User ID
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    userId?: number;

    /**
     * Organization ID
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    orgId?: number;

    /**
     * domain name
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    host?: string | null;

    /**
     * @type {TenantTypeEnum}
     * @memberof AddTenantInput
     */
    tenantType?: TenantTypeEnum;

    /**
     * @type {DbType}
     * @memberof AddTenantInput
     */
    dbType?: DbType;

    /**
     * Database connection
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    connection?: string | null;

    /**
     * Database ID
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    configId?: string | null;

    /**
     * Slave connection / read-write separation
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    slaveConnections?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof AddTenantInput
     */
    enableReg?: YesNoEnum;

    /**
     * Default registration schemeId
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    regWayId?: number | null;

    /**
     * icon
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    logo?: string | null;

    /**
     * Watermark
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    watermark?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof AddTenantInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    remark?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof AddTenantInput
     */
    status?: StatusEnum;

    /**
     * electricitychildEmail
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    email?: string | null;

    /**
     * Telephone
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    phone?: string | null;

    /**
     * Tenant name
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    name: string;

    /**
     * Rental account
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    adminAccount: string;

    /**
     * System Main Title
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    title?: string | null;

    /**
     * System Subtitle
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    viceTitle?: string | null;

    /**
     * System description
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    viceDesc?: string | null;

    /**
     * Copyright statement
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    copyright?: string | null;

    /**
     * ICP Filing Number
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    icp?: string | null;

    /**
     * ICP address
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    icpUrl?: string | null;

    /**
     * LogoPictureBase64code
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    logoBase64?: string | null;

    /**
     * LogoFile name
     *
     * @type {string}
     * @memberof AddTenantInput
     */
    logoFileName?: string | null;
}
