/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PrintTypeEnum } from './print-type-enum';
import { StatusEnum } from './status-enum';
 /**
 * 
 *
 * @export
 * @interface AddPrintInput
 */
export interface AddPrintInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddPrintInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof AddPrintInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof AddPrintInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof AddPrintInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof AddPrintInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof AddPrintInput
     */
    tenantId?: number | null;

    /**
     * Print template
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    template: string;

    /**
     * @type {PrintTypeEnum}
     * @memberof AddPrintInput
     */
    printType: PrintTypeEnum;

    /**
     * Client service address
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    clientServiceAddress?: string | null;

    /**
     * Print parameters
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    printParam?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof AddPrintInput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof AddPrintInput
     */
    status?: StatusEnum;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    remark?: string | null;

    /**
     * Print Preview Test Data
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    printDataDemo?: string | null;

    /**
     * name
     *
     * @type {string}
     * @memberof AddPrintInput
     */
    name: string;
}
