/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysRegion } from './sys-region';
 /**
 * 
 *
 * @export
 * @interface AddRegionInput
 */
export interface AddRegionInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    id?: number;

    /**
     * Parent ID
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    pid?: number;

    /**
     * abbreviation
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    shortName?: string | null;

    /**
     * Group name
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    mergerName?: string | null;

    /**
     * Administrative code
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    code?: string | null;

    /**
     * Postal code
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    zipCode?: string | null;

    /**
     * Area code
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    cityCode?: string | null;

    /**
     * Hierarchy
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    level?: number;

    /**
     * Pinyin
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    pinYin?: string | null;

    /**
     * longitude
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    lng?: number;

    /**
     * Dimension
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    lat?: number;

    /**
     * Sort
     *
     * @type {number}
     * @memberof AddRegionInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    remark?: string | null;

    /**
     * mechanismchilditem
     *
     * @type {Array<SysRegion>}
     * @memberof AddRegionInput
     */
    children?: Array<SysRegion> | null;

    /**
     * name
     *
     * @type {string}
     * @memberof AddRegionInput
     */
    name: string;
}
