/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
 /**
 * 
 *
 * @export
 * @interface AddPluginInput
 */
export interface AddPluginInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddPluginInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof AddPluginInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof AddPluginInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof AddPluginInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof AddPluginInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof AddPluginInput
     */
    tenantId?: number | null;

    /**
     * C# code
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    csharpCode: string;

    /**
     * Assembly Name
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    assemblyName?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof AddPluginInput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof AddPluginInput
     */
    status?: StatusEnum;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    remark?: string | null;

    /**
     * name
     *
     * @type {string}
     * @memberof AddPluginInput
     */
    name: string;
}
