/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountTypeEnum } from './account-type-enum';
 /**
 * Registration planincreaseInputParameter
 *
 * @export
 * @interface AddUserRegWayInput
 */
export interface AddUserRegWayInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof AddUserRegWayInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof AddUserRegWayInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof AddUserRegWayInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof AddUserRegWayInput
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    tenantId?: number | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof AddUserRegWayInput
     */
    remark?: string | null;

    /**
     * Plan Name
     *
     * @type {string}
     * @memberof AddUserRegWayInput
     */
    name: string;

    /**
     * @type {AccountTypeEnum}
     * @memberof AddUserRegWayInput
     */
    accountType?: AccountTypeEnum;

    /**
     * Role
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    roleId: number;

    /**
     * mechanism
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    orgId: number;

    /**
     * Position
     *
     * @type {number}
     * @memberof AddUserRegWayInput
     */
    posId: number;
}
