/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TriggerStatus } from './trigger-status';
 /**
 * 
 *
 * @export
 * @interface AddJobTriggerInput
 */
export interface AddJobTriggerInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    id?: number;

    /**
     * Trigger typeFullName
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    triggerType?: string | null;

    /**
     * AssemblyName
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    assemblyName?: string | null;

    /**
     * Parameter
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    args?: string | null;

    /**
     * Description information
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    description?: string | null;

    /**
     * @type {TriggerStatus}
     * @memberof AddJobTriggerInput
     */
    status?: TriggerStatus;

    /**
     * start time
     *
     * @type {Date}
     * @memberof AddJobTriggerInput
     */
    startTime?: Date | null;

    /**
     * end time
     *
     * @type {Date}
     * @memberof AddJobTriggerInput
     */
    endTime?: Date | null;

    /**
     * Recent run time
     *
     * @type {Date}
     * @memberof AddJobTriggerInput
     */
    lastRunTime?: Date | null;

    /**
     * Next Run Time
     *
     * @type {Date}
     * @memberof AddJobTriggerInput
     */
    nextRunTime?: Date | null;

    /**
     * Number of triggers
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    numberOfRuns?: number;

    /**
     * Maximum trigger count（0:No restrictions，n:Ntime）
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    maxNumberOfRuns?: number;

    /**
     * Number of errors
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    numberOfErrors?: number;

    /**
     * Maximum number of errors（0:No restrictions，n:Ntime）
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    maxNumberOfErrors?: number;

    /**
     * Number of retries
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    numRetries?: number;

    /**
     * Retryintervaltimespace（ms）
     *
     * @type {number}
     * @memberof AddJobTriggerInput
     */
    retryTimeout?: number;

    /**
     * Whether to start immediately
     *
     * @type {boolean}
     * @memberof AddJobTriggerInput
     */
    startNow?: boolean;

    /**
     * Whether to execute once at startup
     *
     * @type {boolean}
     * @memberof AddJobTriggerInput
     */
    runOnStart?: boolean;

    /**
     * YesnoStartingtimeresetMaximum trigger countequalsonenext homework
     *
     * @type {boolean}
     * @memberof AddJobTriggerInput
     */
    resetOnlyOnce?: boolean;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof AddJobTriggerInput
     */
    updatedTime?: Date | null;

    /**
     * JobId
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    jobId: string;

    /**
     * Trigger ID
     *
     * @type {string}
     * @memberof AddJobTriggerInput
     */
    triggerId: string;
}
