/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExtUserInfo } from './ext-user-info';
import { ExtendParams } from './extend-params';
import { InvoiceInfo } from './invoice-info';
 /**
 * Unified order placement and payment page interfaceInputParameter
 *
 * @export
 * @interface AlipayTradePagePayInput
 */
export interface AlipayTradePagePayInput {

    /**
     * Merchant Order Number
     *
     * @type {string}
     * @memberof AlipayTradePagePayInput
     */
    outTradeNo: string;

    /**
     * Total Order Amount
     *
     * @type {string}
     * @memberof AlipayTradePagePayInput
     */
    totalAmount: string;

    /**
     * Ordertitle
     *
     * @type {string}
     * @memberof AlipayTradePagePayInput
     */
    subject: string;

    /**
     * @type {string}
     * @memberof AlipayTradePagePayInput
     */
    body?: string | null;

    /**
     * Supertimetimespace
     *
     * @type {string}
     * @memberof AlipayTradePagePayInput
     */
    timeoutExpress?: string | null;

    /**
     * QR codeWidth
     *
     * @type {number}
     * @memberof AlipayTradePagePayInput
     */
    qrcodeWidth: number;

    /**
     * @type {ExtendParams}
     * @memberof AlipayTradePagePayInput
     */
    extendParams?: ExtendParams;

    /**
     * Merchant BusinessData
     *
     * @type {{ [key: string]: any; }}
     * @memberof AlipayTradePagePayInput
     */
    businessParams?: { [key: string]: any; } | null;

    /**
     * @type {InvoiceInfo}
     * @memberof AlipayTradePagePayInput
     */
    invoiceInfo?: InvoiceInfo;

    /**
     * @type {ExtUserInfo}
     * @memberof AlipayTradePagePayInput
     */
    extUserInfo?: ExtUserInfo;
}
