/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * code generationDetailedConfigurationParameter
 *
 * @export
 * @interface CodeGenConfig
 */
export interface CodeGenConfig {

    /**
     * Primary keyId
     *
     * @type {number}
     * @memberof CodeGenConfig
     */
    id?: number;

    /**
     * code generationMain TableID
     *
     * @type {number}
     * @memberof CodeGenConfig
     */
    codeGenId?: number;

    /**
     * DataWarehouseField Name
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnName?: string | null;

    /**
     * Masterforeign key
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnKey?: string | null;

    /**
     * Entity attributeName
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    propertyName?: string | null;

    /**
     * Field data length
     *
     * @type {number}
     * @memberof CodeGenConfig
     */
    columnLength?: number;

    /**
     * DataWarehouseField Name(lowercase first letter)
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerPropertyName?: string | null;

    /**
     * FieldDescription
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnComment?: string | null;

    /**
     * .NETType
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    netType?: string | null;

    /**
     * DataWarehouseinType（PhysicsType）
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    dataType?: string | null;

    /**
     * FieldDataDefault value
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    defaultValue?: string | null;

    /**
     * Nullable.NETType
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    nullableNetType?: string | null;

    /**
     * Type of effect（dictionary）
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    effectType?: string | null;

    /**
     * Foreign key library identifier
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkConfigId?: string | null;

    /**
     * Foreign key entity name
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkEntityName?: string | null;

    /**
     * Foreign key table name
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkTableName?: string | null;

    /**
     * Foreign key entity name(lowercase first letter)
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerFkEntityName?: string | null;

    /**
     * Foreign key link field
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkLinkColumnName?: string | null;

    /**
     * Foreign key display field
     *
     * @type {Array<string>}
     * @memberof CodeGenConfig
     */
    fkDisplayColumnList?: Array<string> | null;

    /**
     * Foreign key display field(lowercase first letter)
     *
     * @type {Array<string>}
     * @memberof CodeGenConfig
     */
    lowerFkDisplayColumnsList?: Array<string> | null;

    /**
     * Foreign key display field .NET type
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkColumnNetType?: string | null;

    /**
     * Parent field
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    pidColumn?: string | null;

    /**
     * dictionarycode
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    dictTypeCode?: string | null;

    /**
     * Query method
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    queryType?: string | null;

    /**
     * Is it a query condition?
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherQuery?: string | null;

    /**
     * Whether the list is indented（dictionary）
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherRetract?: string | null;

    /**
     * Is it required?（dictionary）
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherRequired?: string | null;

    /**
     * Is it sortable?（dictionary）
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherSortable?: string | null;

    /**
     * List Display
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherTable?: string | null;

    /**
     * Additions and changes
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherAddUpdate?: string | null;

    /**
     * import
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherImport?: string | null;

    /**
     * YesnoYesGeneralField
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherCommon?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof CodeGenConfig
     */
    orderNo?: number;

    /**
     * YesnoYesSelector control
     *
     * @type {boolean}
     * @memberof CodeGenConfig
     */
    isSelectorEffectType?: boolean;

    /**
     * Remove the tailIdofAttributeName
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    propertyNameTrimEndId?: string | null;

    /**
     * Remove the tailIdofAttributeName
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerPropertyNameTrimEndId?: string | null;

    /**
     * ExpandAttributename
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    extendedPropertyName?: string | null;

    /**
     * Extension with lowercase initialAttributename
     *
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerExtendedPropertyName?: string | null;
}
