/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Educational Level Enumeration<br />&nbsp;Other Level0 = 0<br />&nbsp;Illiteracy Level1 = 1<br /> Elementary School Level 2 = 2<br />  Junior High Level 3 = 3<br /> General High School Level 4 = 4<br />&nbsp;Technical School Level 5 = 5<br />&nbsp;Vocational Education Level6 = 6<br />&nbsp;Vocational High School Level7 = 7<br />&nbsp;Secondary College Level8 = 8<br />&nbsp;College College Level9 = 9<br />&nbsp;Undergraduate Level10 = 10<br />&nbsp;Master's Degree Graduate Level11 = 11<br /> Doctoral student Level12 = 12<br />
 * @export
 * @enum {string}
 */
export enum CultureLevelEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12
}

