/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MenuOutput } from './menu-output';
import { MenuTypeEnum } from './menu-type-enum';
import { StatusEnum } from './status-enum';
import { SysMenuMeta } from './sys-menu-meta';
 /**
 * systemmenuReturn result
 *
 * @export
 * @interface MenuOutput
 */
export interface MenuOutput {

    /**
     * Id
     *
     * @type {number}
     * @memberof MenuOutput
     */
    id?: number;

    /**
     * Parent ID
     *
     * @type {number}
     * @memberof MenuOutput
     */
    pid?: number;

    /**
     * @type {MenuTypeEnum}
     * @memberof MenuOutput
     */
    type?: MenuTypeEnum;

    /**
     * name
     *
     * @type {string}
     * @memberof MenuOutput
     */
    name?: string | null;

    /**
     * Routing Address
     *
     * @type {string}
     * @memberof MenuOutput
     */
    path?: string | null;

    /**
     * component path
     *
     * @type {string}
     * @memberof MenuOutput
     */
    component?: string | null;

    /**
     * Permission Identifier
     *
     * @type {string}
     * @memberof MenuOutput
     */
    permission?: string | null;

    /**
     * Redirect
     *
     * @type {string}
     * @memberof MenuOutput
     */
    redirect?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof MenuOutput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof MenuOutput
     */
    status?: StatusEnum;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof MenuOutput
     */
    remark?: string | null;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof MenuOutput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof MenuOutput
     */
    updateTime?: Date;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof MenuOutput
     */
    createUserName?: string | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof MenuOutput
     */
    updateUserName?: string | null;

    /**
     * @type {SysMenuMeta}
     * @memberof MenuOutput
     */
    meta?: SysMenuMeta;

    /**
     * menuchilditem
     *
     * @type {Array<MenuOutput>}
     * @memberof MenuOutput
     */
    children?: Array<MenuOutput> | null;
}
