/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * Translation TablepointsPageQueryInputParameter
 *
 * @export
 * @interface PageSysLangTextInput
 */
export interface PageSysLangTextInput {

    /**
     * @type {Search}
     * @memberof PageSysLangTextInput
     */
    search?: Search;

    /**
     * BlurryQueryKeywords
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageSysLangTextInput
     */
    filter?: Filter;

    /**
     * Current page number
     *
     * @type {number}
     * @memberof PageSysLangTextInput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof PageSysLangTextInput
     */
    pageSize?: number;

    /**
     * SortField
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    field?: string | null;

    /**
     * SortDirection
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    order?: string | null;

    /**
     * Descending orderSort
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    descStr?: string | null;

    /**
     * Name of the affiliated entity
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    entityName?: string | null;

    /**
     * Associated Entity ID
     *
     * @type {number}
     * @memberof PageSysLangTextInput
     */
    entityId?: number | null;

    /**
     * Field Name
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    fieldName?: string | null;

    /**
     * Language code
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    langCode?: string | null;

    /**
     * Translate content
     *
     * @type {string}
     * @memberof PageSysLangTextInput
     */
    content?: string | null;

    /**
     * SelectinPrimary KeyList
     *
     * @type {Array<number>}
     * @memberof PageSysLangTextInput
     */
    selectKeyList?: Array<number> | null;
}
