/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface PageRegionInput
 */
export interface PageRegionInput {

    /**
     * @type {Search}
     * @memberof PageRegionInput
     */
    search?: Search;

    /**
     * BlurryQueryKeywords
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageRegionInput
     */
    filter?: Filter;

    /**
     * Current page number
     *
     * @type {number}
     * @memberof PageRegionInput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof PageRegionInput
     */
    pageSize?: number;

    /**
     * SortField
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    field?: string | null;

    /**
     * SortDirection
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    order?: string | null;

    /**
     * Descending orderSort
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    descStr?: string | null;

    /**
     * Parent nodeId
     *
     * @type {number}
     * @memberof PageRegionInput
     */
    pid?: number;

    /**
     * name
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    name?: string | null;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof PageRegionInput
     */
    code?: string | null;
}
