/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * manyLanguagepointsPageQueryInputParameter
 *
 * @export
 * @interface PageSysLangInput
 */
export interface PageSysLangInput {

    /**
     * @type {Search}
     * @memberof PageSysLangInput
     */
    search?: Search;

    /**
     * BlurryQueryKeywords
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageSysLangInput
     */
    filter?: Filter;

    /**
     * Current page number
     *
     * @type {number}
     * @memberof PageSysLangInput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof PageSysLangInput
     */
    pageSize?: number;

    /**
     * SortField
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    field?: string | null;

    /**
     * SortDirection
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    order?: string | null;

    /**
     * Descending orderSort
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    descStr?: string | null;

    /**
     * Language name
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    name?: string | null;

    /**
     * Language code
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    code?: string | null;

    /**
     * ISO language code
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    isoCode?: string | null;

    /**
     * URL language code
     *
     * @type {string}
     * @memberof PageSysLangInput
     */
    urlCode?: string | null;

    /**
     * Enable or not
     *
     * @type {boolean}
     * @memberof PageSysLangInput
     */
    active?: boolean | null;

    /**
     * SelectinPrimary KeyList
     *
     * @type {Array<number>}
     * @memberof PageSysLangInput
     */
    selectKeyList?: Array<number> | null;
}
