/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysLdap } from './sys-ldap';
 /**
 * pointsPaged generic collection
 *
 * @export
 * @interface SqlSugarPagedListSysLdap
 */
export interface SqlSugarPagedListSysLdap {

    /**
     * Page number
     *
     * @type {number}
     * @memberof SqlSugarPagedListSysLdap
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof SqlSugarPagedListSysLdap
     */
    pageSize?: number;

    /**
     * Total number of items
     *
     * @type {number}
     * @memberof SqlSugarPagedListSysLdap
     */
    total?: number;

    /**
     * Total Pages
     *
     * @type {number}
     * @memberof SqlSugarPagedListSysLdap
     */
    totalPages?: number;

    /**
     * Current Page Collection
     *
     * @type {Array<SysLdap>}
     * @memberof SqlSugarPagedListSysLdap
     */
    items?: Array<SysLdap> | null;

    /**
     * YesnoThere is an uponePage
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListSysLdap
     */
    hasPrevPage?: boolean;

    /**
     * YesnoThere is belowonePage
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListSysLdap
     */
    hasNextPage?: boolean;
}
