/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JobDetailOutput } from './job-detail-output';
 /**
 * pointsPaged generic collection
 *
 * @export
 * @interface SqlSugarPagedListJobDetailOutput
 */
export interface SqlSugarPagedListJobDetailOutput {

    /**
     * Page number
     *
     * @type {number}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    pageSize?: number;

    /**
     * Total number of items
     *
     * @type {number}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    total?: number;

    /**
     * Total Pages
     *
     * @type {number}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    totalPages?: number;

    /**
     * Current Page Collection
     *
     * @type {Array<JobDetailOutput>}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    items?: Array<JobDetailOutput> | null;

    /**
     * YesnoThere is an uponePage
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    hasPrevPage?: boolean;

    /**
     * YesnoThere is belowonePage
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListJobDetailOutput
     */
    hasNextPage?: boolean;
}
