/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeyValuePairStringString } from './key-value-pair-string-string';
 /**
 * Interface pressure testInputParameter
 *
 * @export
 * @interface StressTestInput
 */
export interface StressTestInput {

    /**
     * InterfaceRequest address
     *
     * @type {string}
     * @memberof StressTestInput
     * @example https://gitee.com/zuohuaijun/Admin.NET
     */
    requestUri: string;

    /**
     * Request Method
     *
     * @type {string}
     * @memberof StressTestInput
     */
    requestMethod: string;

    /**
     * Requests per round
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 100
     */
    numberOfRequests: number;

    /**
     * Stress testingNumber of rounds
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 5
     */
    numberOfRounds: number;

    /**
     * MaximumParallelAmount（Defaultfor the currentHostLogicProcessorofquantity）
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 500
     */
    maxDegreeOfParallelism?: number | null;

    /**
     * Request parameters
     *
     * @type {Array<KeyValuePairStringString>}
     * @memberof StressTestInput
     */
    requestParameters?: Array<KeyValuePairStringString> | null;

    /**
     * Request HeaderParameter
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    headers?: { [key: string]: string; } | null;

    /**
     * PathParameter
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    pathParameters?: { [key: string]: string; } | null;

    /**
     * QueryParameter
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    _queryParameters?: { [key: string]: string; } | null;
}
