/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Interface pressure testOutputParameter
 *
 * @export
 * @interface StressTestOutput
 */
export interface StressTestOutput {

    /**
     * Total number of requests
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    totalRequests?: number;

    /**
     * Total Time (seconds)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    totalTimeInSeconds?: number;

    /**
     * Number of successful requests
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    successfulRequests?: number;

    /**
     * Number of failed requests
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    failedRequests?: number;

    /**
     * Query rate per second (QPS)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    queriesPerSecond?: number;

    /**
     * Minimum response time (milliseconds)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    minResponseTime?: number;

    /**
     * Maximum response time (milliseconds)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    maxResponseTime?: number;

    /**
     * Average response time (milliseconds)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    averageResponseTime?: number;

    /**
     * P10 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile10ResponseTime?: number;

    /**
     * P25 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile25ResponseTime?: number;

    /**
     * P50 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile50ResponseTime?: number;

    /**
     * P75 responsetimespace（millimetersecond）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile75ResponseTime?: number;

    /**
     * P90 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile90ResponseTime?: number;

    /**
     * P99 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile99ResponseTime?: number;

    /**
     * P999 Response Time (ms)
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile999ResponseTime?: number;
}
