/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LogLevel } from './log-level';
 /**
 * System operation log table
 *
 * @export
 * @interface SysLogOp
 */
export interface SysLogOp {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysLogOp
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysLogOp
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysLogOp
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysLogOp
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysLogOp
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof SysLogOp
     */
    tenantId?: number | null;

    /**
     * Module Name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    controllerName?: string | null;

    /**
     * Method Name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    actionName?: string | null;

    /**
     * Display Name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    displayTitle?: string | null;

    /**
     * Execution Status
     *
     * @type {string}
     * @memberof SysLogOp
     */
    status?: string | null;

    /**
     * IP address
     *
     * @type {string}
     * @memberof SysLogOp
     */
    remoteIp?: string | null;

    /**
     * Login location
     *
     * @type {string}
     * @memberof SysLogOp
     */
    location?: string | null;

    /**
     * longitude
     *
     * @type {number}
     * @memberof SysLogOp
     */
    longitude?: number | null;

    /**
     * Dimension
     *
     * @type {number}
     * @memberof SysLogOp
     */
    latitude?: number | null;

    /**
     * Browser
     *
     * @type {string}
     * @memberof SysLogOp
     */
    browser?: string | null;

    /**
     * operating system
     *
     * @type {string}
     * @memberof SysLogOp
     */
    os?: string | null;

    /**
     * Operation time
     *
     * @type {number}
     * @memberof SysLogOp
     */
    elapsed?: number | null;

    /**
     * Log Time
     *
     * @type {Date}
     * @memberof SysLogOp
     */
    logDateTime?: Date | null;

    /**
     * @type {LogLevel}
     * @memberof SysLogOp
     */
    logLevel?: LogLevel;

    /**
     * Account number
     *
     * @type {string}
     * @memberof SysLogOp
     */
    account?: string | null;

    /**
     * Real Name
     *
     * @type {string}
     * @memberof SysLogOp
     */
    realName?: string | null;

    /**
     * Request Method
     *
     * @type {string}
     * @memberof SysLogOp
     */
    httpMethod?: string | null;

    /**
     * Request address
     *
     * @type {string}
     * @memberof SysLogOp
     */
    requestUrl?: string | null;

    /**
     * Request parameters
     *
     * @type {string}
     * @memberof SysLogOp
     */
    requestParam?: string | null;

    /**
     * Return result
     *
     * @type {string}
     * @memberof SysLogOp
     */
    returnResult?: string | null;

    /**
     * Event ID
     *
     * @type {number}
     * @memberof SysLogOp
     */
    eventId?: number | null;

    /**
     * ThreadId
     *
     * @type {number}
     * @memberof SysLogOp
     */
    threadId?: number | null;

    /**
     * Request Tracking ID
     *
     * @type {string}
     * @memberof SysLogOp
     */
    traceId?: string | null;

    /**
     * Exception information
     *
     * @type {string}
     * @memberof SysLogOp
     */
    exception?: string | null;

    /**
     * Log message Json
     *
     * @type {string}
     * @memberof SysLogOp
     */
    message?: string | null;
}
