/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * System WeChat payment refund form
 *
 * @export
 * @interface SysWechatRefund
 */
export interface SysWechatRefund {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysWechatRefund
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysWechatRefund
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysWechatRefund
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysWechatRefund
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysWechatRefund
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    updateUserName?: string | null;

    /**
     * Order Primary Key
     *
     * @type {number}
     * @memberof SysWechatRefund
     */
    wechatPayId?: number;

    /**
     * Merchant refund number
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    outRefundNumber: string;

    /**
     * RefundOrder Number
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    transactionId: string;

    /**
     * Reason for refund
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    reason?: string | null;

    /**
     * Refund channels
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    channel?: string | null;

    /**
     * Refund into account
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    userReceivedAccount?: string | null;

    /**
     * Refund status
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    tradeState?: string | null;

    /**
     * Transaction status description
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    tradeStateDescription?: string | null;

    /**
     * Total Order Amount
     *
     * @type {number}
     * @memberof SysWechatRefund
     */
    refund?: number;

    /**
     * branchcompletion time
     *
     * @type {Date}
     * @memberof SysWechatRefund
     */
    successTime?: Date | null;

    /**
     * Callback notification address
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    notifyUrl?: string | null;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof SysWechatRefund
     */
    remark?: string | null;
}
