/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Code Generation Field Configuration Table
 *
 * @export
 * @interface SysCodeGenConfig
 */
export interface SysCodeGenConfig {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysCodeGenConfig
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysCodeGenConfig
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    updateUserName?: string | null;

    /**
     * code generationMain table ID
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    codeGenId?: number;

    /**
     * DataWarehouseField Name
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnName: string;

    /**
     * Primary Key
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnKey?: string | null;

    /**
     * Entity attributeName
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    propertyName: string;

    /**
     * Field data length
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    columnLength?: number;

    /**
     * FieldDescription
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnComment?: string | null;

    /**
     * DataWarehouseinType（PhysicsType）
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dataType?: string | null;

    /**
     * .NET Data Types
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    netType?: string | null;

    /**
     * FieldDataDefault value
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    defaultValue?: string | null;

    /**
     * Type of effect（dictionary）
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    effectType?: string | null;

    /**
     * Foreign key library identifier
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkConfigId?: string | null;

    /**
     * Foreign key entity name
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkEntityName?: string | null;

    /**
     * Foreign key table name
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkTableName?: string | null;

    /**
     * Foreign key display field
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkDisplayColumns?: string | null;

    /**
     * Foreign key link field
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkLinkColumnName?: string | null;

    /**
     * Foreign key display field .NET type
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkColumnNetType?: string | null;

    /**
     * Parent field
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    pidColumn?: string | null;

    /**
     * Dictionary Encoding
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dictTypeCode?: string | null;

    /**
     * Query method
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    queryType?: string | null;

    /**
     * Is it a query condition?
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherQuery?: string | null;

    /**
     * Whether the list is indented（dictionary）
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRetract?: string | null;

    /**
     * Is it required?（dictionary）
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRequired?: string | null;

    /**
     * Is it sortable?（dictionary）
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherSortable?: string | null;

    /**
     * List Display
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherTable?: string | null;

    /**
     * Additions and changes
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherAddUpdate?: string | null;

    /**
     * import
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherImport?: string | null;

    /**
     * Is it a common field?
     *
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherCommon?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    orderNo?: number;
}
