/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PlatformTypeEnum } from './platform-type-enum';
 /**
 * System WeChat user table
 *
 * @export
 * @interface SysWechatUser
 */
export interface SysWechatUser {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysWechatUser
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysWechatUser
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    updateUserName?: string | null;

    /**
     * System User ID
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    userId?: number;

    /**
     * @type {PlatformTypeEnum}
     * @memberof SysWechatUser
     */
    platformType?: PlatformTypeEnum;

    /**
     * OpenId
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    openId: string;

    /**
     * Session key
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    sessionKey?: string | null;

    /**
     * UnionId
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    unionId?: string | null;

    /**
     * Nickname
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    nickName?: string | null;

    /**
     * Avatar
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    avatar?: string | null;

    /**
     * Mobile phone number
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    mobile?: string | null;

    /**
     * gender
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    sex?: number | null;

    /**
     * Language
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    language?: string | null;

    /**
     * city
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    city?: string | null;

    /**
     * Province
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    province?: string | null;

    /**
     * Country
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    country?: string | null;

    /**
     * AccessToken
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    accessToken?: string | null;

    /**
     * RefreshToken
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    refreshToken?: string | null;

    /**
     * Expiredtimespace
     *
     * @type {number}
     * @memberof SysWechatUser
     */
    expiresIn?: number | null;

    /**
     * UserAuthorizationscope，Use a commapointsto separate
     *
     * @type {string}
     * @memberof SysWechatUser
     */
    scope?: string | null;
}
