/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateTypeEnum } from './template-type-enum';
 /**
 * System Template Table
 *
 * @export
 * @interface SysTemplate
 */
export interface SysTemplate {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysTemplate
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysTemplate
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysTemplate
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysTemplate
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysTemplate
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysTemplate
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysTemplate
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof SysTemplate
     */
    tenantId?: number | null;

    /**
     * name
     *
     * @type {string}
     * @memberof SysTemplate
     */
    name?: string | null;

    /**
     * @type {TemplateTypeEnum}
     * @memberof SysTemplate
     */
    type?: TemplateTypeEnum;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof SysTemplate
     */
    code?: string | null;

    /**
     * Group Name
     *
     * @type {string}
     * @memberof SysTemplate
     */
    groupName?: string | null;

    /**
     * Template content
     *
     * @type {string}
     * @memberof SysTemplate
     */
    content?: string | null;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof SysTemplate
     */
    remark?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof SysTemplate
     */
    orderNo?: number;
}
