/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
 /**
 * System Dictionary Value Table
 *
 * @export
 * @interface SysDictData
 */
export interface SysDictData {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysDictData
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysDictData
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysDictData
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysDictData
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysDictData
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysDictData
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysDictData
     */
    updateUserName?: string | null;

    /**
     * Dictionary Type Id
     *
     * @type {number}
     * @memberof SysDictData
     */
    dictTypeId?: number;

    /**
     * Display Text
     *
     * @type {string}
     * @memberof SysDictData
     */
    label: string;

    /**
     * value
     *
     * @type {string}
     * @memberof SysDictData
     */
    value: string;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof SysDictData
     */
    code?: string | null;

    /**
     * name
     *
     * @type {string}
     * @memberof SysDictData
     */
    name?: string | null;

    /**
     * Display style-label color
     *
     * @type {string}
     * @memberof SysDictData
     */
    tagType?: string | null;

    /**
     * Display style-Style(ControlDisplayStyle)
     *
     * @type {string}
     * @memberof SysDictData
     */
    styleSetting?: string | null;

    /**
     * DisplayStyle-Class(ControlDisplayStyle)
     *
     * @type {string}
     * @memberof SysDictData
     */
    classSetting?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof SysDictData
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof SysDictData
     */
    remark?: string | null;

    /**
     * Expansion data (save configuration items for business functions)
     *
     * @type {string}
     * @memberof SysDictData
     */
    extData?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof SysDictData
     */
    status?: StatusEnum;
}
