/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FinishStatusEnum } from './finish-status-enum';
 /**
 * System schedule
 *
 * @export
 * @interface SysSchedule
 */
export interface SysSchedule {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysSchedule
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysSchedule
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysSchedule
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysSchedule
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysSchedule
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysSchedule
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysSchedule
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof SysSchedule
     */
    tenantId?: number | null;

    /**
     * UserId
     *
     * @type {number}
     * @memberof SysSchedule
     */
    userId?: number;

    /**
     * Schedule Date
     *
     * @type {Date}
     * @memberof SysSchedule
     */
    scheduleTime?: Date | null;

    /**
     * start time
     *
     * @type {string}
     * @memberof SysSchedule
     */
    startTime?: string | null;

    /**
     * end time
     *
     * @type {string}
     * @memberof SysSchedule
     */
    endTime?: string | null;

    /**
     * Schedule content
     *
     * @type {string}
     * @memberof SysSchedule
     */
    content: string;

    /**
     * @type {FinishStatusEnum}
     * @memberof SysSchedule
     */
    status?: FinishStatusEnum;
}
