/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DirectionEnum } from './direction-enum';
import { WeekEnum } from './week-enum';
 /**
 * 
 *
 * @export
 * @interface SysLang
 */
export interface SysLang {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysLang
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysLang
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysLang
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysLang
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysLang
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysLang
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysLang
     */
    updateUserName?: string | null;

    /**
     * Language name
     *
     * @type {string}
     * @memberof SysLang
     */
    name?: string | null;

    /**
     * Language code（such as zh-CN）
     *
     * @type {string}
     * @memberof SysLang
     */
    code?: string | null;

    /**
     * ISO language code
     *
     * @type {string}
     * @memberof SysLang
     */
    isoCode?: string | null;

    /**
     * URL language code
     *
     * @type {string}
     * @memberof SysLang
     */
    urlCode?: string | null;

    /**
     * @type {DirectionEnum}
     * @memberof SysLang
     */
    direction?: DirectionEnum;

    /**
     * date format（such as YYYY-MM-DD）
     *
     * @type {string}
     * @memberof SysLang
     */
    dateFormat?: string | null;

    /**
     * time format（such as HH:MM:SS）
     *
     * @type {string}
     * @memberof SysLang
     */
    timeFormat?: string | null;

    /**
     * @type {WeekEnum}
     * @memberof SysLang
     */
    weekStart?: WeekEnum;

    /**
     * Grouping symbols（such as ,）
     *
     * @type {string}
     * @memberof SysLang
     */
    grouping?: string | null;

    /**
     * Decimal point symbol
     *
     * @type {string}
     * @memberof SysLang
     */
    decimalPoint?: string | null;

    /**
     * thousands separator
     *
     * @type {string}
     * @memberof SysLang
     */
    thousandsSep?: string | null;

    /**
     * Enable or not
     *
     * @type {boolean}
     * @memberof SysLang
     */
    active?: boolean;
}
