/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { YesNoEnum } from './yes-no-enum';
 /**
 * System Configuration Parameter Table
 *
 * @export
 * @interface SysConfig
 */
export interface SysConfig {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof SysConfig
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof SysConfig
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof SysConfig
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof SysConfig
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof SysConfig
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof SysConfig
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof SysConfig
     */
    updateUserName?: string | null;

    /**
     * name
     *
     * @type {string}
     * @memberof SysConfig
     */
    name: string;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof SysConfig
     */
    code?: string | null;

    /**
     * Parameter value
     *
     * @type {string}
     * @memberof SysConfig
     */
    value?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof SysConfig
     */
    sysFlag?: YesNoEnum;

    /**
     * GroupEncoding
     *
     * @type {string}
     * @memberof SysConfig
     */
    groupCode?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof SysConfig
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof SysConfig
     */
    remark?: string | null;
}
