/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DbType } from './db-type';
import { StatusEnum } from './status-enum';
import { TenantTypeEnum } from './tenant-type-enum';
import { YesNoEnum } from './yes-no-enum';
 /**
 * 
 *
 * @export
 * @interface TenantOutput
 */
export interface TenantOutput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof TenantOutput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof TenantOutput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof TenantOutput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof TenantOutput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof TenantOutput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof TenantOutput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof TenantOutput
     */
    updateUserName?: string | null;

    /**
     * Rent-controlled User ID
     *
     * @type {number}
     * @memberof TenantOutput
     */
    userId?: number;

    /**
     * Organization ID
     *
     * @type {number}
     * @memberof TenantOutput
     */
    orgId?: number;

    /**
     * domain name
     *
     * @type {string}
     * @memberof TenantOutput
     */
    host?: string | null;

    /**
     * @type {TenantTypeEnum}
     * @memberof TenantOutput
     */
    tenantType?: TenantTypeEnum;

    /**
     * @type {DbType}
     * @memberof TenantOutput
     */
    dbType?: DbType;

    /**
     * Database connection
     *
     * @type {string}
     * @memberof TenantOutput
     */
    connection?: string | null;

    /**
     * Database ID
     *
     * @type {string}
     * @memberof TenantOutput
     */
    configId?: string | null;

    /**
     * Slave connection / read-write separation
     *
     * @type {string}
     * @memberof TenantOutput
     */
    slaveConnections?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof TenantOutput
     */
    enableReg?: YesNoEnum;

    /**
     * Default registration schemeId
     *
     * @type {number}
     * @memberof TenantOutput
     */
    regWayId?: number | null;

    /**
     * icon
     *
     * @type {string}
     * @memberof TenantOutput
     */
    logo?: string | null;

    /**
     * title
     *
     * @type {string}
     * @memberof TenantOutput
     */
    title?: string | null;

    /**
     * Subtitle
     *
     * @type {string}
     * @memberof TenantOutput
     */
    viceTitle?: string | null;

    /**
     * Sub-description
     *
     * @type {string}
     * @memberof TenantOutput
     */
    viceDesc?: string | null;

    /**
     * Watermark
     *
     * @type {string}
     * @memberof TenantOutput
     */
    watermark?: string | null;

    /**
     * Copyright information
     *
     * @type {string}
     * @memberof TenantOutput
     */
    copyright?: string | null;

    /**
     * ICP Filing Number
     *
     * @type {string}
     * @memberof TenantOutput
     */
    icp?: string | null;

    /**
     * ICP address
     *
     * @type {string}
     * @memberof TenantOutput
     */
    icpUrl?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof TenantOutput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof TenantOutput
     */
    remark?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof TenantOutput
     */
    status?: StatusEnum;

    /**
     * Tenant name
     *
     * @type {string}
     * @memberof TenantOutput
     */
    name?: string | null;

    /**
     * AdministratorAccount number
     *
     * @type {string}
     * @memberof TenantOutput
     */
    adminAccount?: string | null;

    /**
     * electricitychildEmail
     *
     * @type {string}
     * @memberof TenantOutput
     */
    email?: string | null;

    /**
     * Telephone
     *
     * @type {string}
     * @memberof TenantOutput
     */
    phone?: string | null;
}
