/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateTypeEnum } from './template-type-enum';
 /**
 * Update templateInputParameter
 *
 * @export
 * @interface UpdateTemplateInput
 */
export interface UpdateTemplateInput {

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateTemplateInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateTemplateInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateTemplateInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateTemplateInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof UpdateTemplateInput
     */
    tenantId?: number | null;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    remark?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UpdateTemplateInput
     */
    orderNo?: number;

    /**
     * name
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    name: string;

    /**
     * @type {TemplateTypeEnum}
     * @memberof UpdateTemplateInput
     */
    type?: TemplateTypeEnum;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    code: string;

    /**
     * Group Name
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    groupName: string;

    /**
     * Template content
     *
     * @type {string}
     * @memberof UpdateTemplateInput
     */
    content: string;

    /**
     * Primary keyId
     *
     * @type {number}
     * @memberof UpdateTemplateInput
     */
    id: number;
}
