/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MenuTypeEnum } from './menu-type-enum';
import { StatusEnum } from './status-enum';
import { SysMenu } from './sys-menu';
 /**
 * 
 *
 * @export
 * @interface UpdateMenuInput
 */
export interface UpdateMenuInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateMenuInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateMenuInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    updateUserName?: string | null;

    /**
     * Parent ID
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    pid?: number;

    /**
     * @type {MenuTypeEnum}
     * @memberof UpdateMenuInput
     */
    type?: MenuTypeEnum;

    /**
     * Route Name
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    name?: string | null;

    /**
     * Routing Address
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    path?: string | null;

    /**
     * component path
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    component?: string | null;

    /**
     * Redirect
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    redirect?: string | null;

    /**
     * Permission Identifier
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    permission?: string | null;

    /**
     * icon
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    icon?: string | null;

    /**
     * YesnoEmbedded
     *
     * @type {boolean}
     * @memberof UpdateMenuInput
     */
    isIframe?: boolean;

    /**
     * External links
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    outLink?: string | null;

    /**
     * Whether to hide
     *
     * @type {boolean}
     * @memberof UpdateMenuInput
     */
    isHide?: boolean;

    /**
     * Whether to cache
     *
     * @type {boolean}
     * @memberof UpdateMenuInput
     */
    isKeepAlive?: boolean;

    /**
     * Is it fixed?
     *
     * @type {boolean}
     * @memberof UpdateMenuInput
     */
    isAffix?: boolean;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof UpdateMenuInput
     */
    status?: StatusEnum;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    remark?: string | null;

    /**
     * menuchilditem
     *
     * @type {Array<SysMenu>}
     * @memberof UpdateMenuInput
     */
    children?: Array<SysMenu> | null;

    /**
     * name
     *
     * @type {string}
     * @memberof UpdateMenuInput
     */
    title: string;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof UpdateMenuInput
     */
    tenantId?: number;
}
