/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountTypeEnum } from './account-type-enum';
 /**
 * Registration planUpdateInputParameter
 *
 * @export
 * @interface UpdateUserRegWayInput
 */
export interface UpdateUserRegWayInput {

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateUserRegWayInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateUserRegWayInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateUserRegWayInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateUserRegWayInput
     */
    updateUserName?: string | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    tenantId?: number | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateUserRegWayInput
     */
    remark?: string | null;

    /**
     * Plan Name
     *
     * @type {string}
     * @memberof UpdateUserRegWayInput
     */
    name: string;

    /**
     * @type {AccountTypeEnum}
     * @memberof UpdateUserRegWayInput
     */
    accountType?: AccountTypeEnum;

    /**
     * Role
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    roleId: number;

    /**
     * mechanism
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    orgId: number;

    /**
     * Position
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    posId: number;

    /**
     * Primary keyId
     *
     * @type {number}
     * @memberof UpdateUserRegWayInput
     */
    id: number;
}
