/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
import { TableUniqueConfigItem } from './table-unique-config-item';
 /**
 * 
 *
 * @export
 * @interface UpdateCodeGenInput
 */
export interface UpdateCodeGenInput {

    /**
     * @type {Search}
     * @memberof UpdateCodeGenInput
     */
    search?: Search;

    /**
     * BlurryQueryKeywords
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof UpdateCodeGenInput
     */
    filter?: Filter;

    /**
     * Current page number
     *
     * @type {number}
     * @memberof UpdateCodeGenInput
     */
    page?: number;

    /**
     * Page capacity
     *
     * @type {number}
     * @memberof UpdateCodeGenInput
     */
    pageSize?: number;

    /**
     * SortField
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    field?: string | null;

    /**
     * SortDirection
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    order?: string | null;

    /**
     * Descending orderSort
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    descStr?: string | null;

    /**
     * Class name
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    className?: string | null;

    /**
     * Whether to remove the table prefix
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    tablePrefix?: string | null;

    /**
     * Library Locator Name
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    configId?: string | null;

    /**
     * DataLibrary name(ReserveField)
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    dbName?: string | null;

    /**
     * Database type
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    dbType?: string | null;

    /**
     * Database link
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    connectionString?: string | null;

    /**
     * Function Name（Database table namecall）
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    tableComment?: string | null;

    /**
     * table onlyoneFieldList
     *
     * @type {Array<TableUniqueConfigItem>}
     * @memberof UpdateCodeGenInput
     */
    tableUniqueList?: Array<TableUniqueConfigItem> | null;

    /**
     * menuApplicationpointsClass（ApplicationEncoding）
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    menuApplication?: string | null;

    /**
     * menuParent
     *
     * @type {number}
     * @memberof UpdateCodeGenInput
     */
    menuPid?: number | null;

    /**
     * Menu icon
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    menuIcon?: string | null;

    /**
     * Page directory
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    pagePath?: string | null;

    /**
     * Supported print types
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    printType?: string | null;

    /**
     * Print Template Name
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    printName?: string | null;

    /**
     * Database table name
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    tableName: string;

    /**
     * Business Name（Business code packagename）
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    busName: string;

    /**
     * namespace
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    nameSpace: string;

    /**
     * Author's Name
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    authorName: string;

    /**
     * Generation method
     *
     * @type {string}
     * @memberof UpdateCodeGenInput
     */
    generateType: string;

    /**
     * Generate menu?
     *
     * @type {boolean}
     * @memberof UpdateCodeGenInput
     */
    generateMenu: boolean;

    /**
     * code generationutensilId
     *
     * @type {number}
     * @memberof UpdateCodeGenInput
     */
    id: number;
}
