/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NoticeStatusEnum } from './notice-status-enum';
import { NoticeTypeEnum } from './notice-type-enum';
 /**
 * 
 *
 * @export
 * @interface UpdateNoticeInput
 */
export interface UpdateNoticeInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateNoticeInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateNoticeInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    updateUserName?: string | null;

    /**
     * title
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    title: string;

    /**
     * content
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    content: string;

    /**
     * @type {NoticeTypeEnum}
     * @memberof UpdateNoticeInput
     */
    type?: NoticeTypeEnum;

    /**
     * PublisherId
     *
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    publicUserId?: number;

    /**
     * Publisher name
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    publicUserName?: string | null;

    /**
     * Issuing Organization Id
     *
     * @type {number}
     * @memberof UpdateNoticeInput
     */
    publicOrgId?: number;

    /**
     * Issuing organization name
     *
     * @type {string}
     * @memberof UpdateNoticeInput
     */
    publicOrgName?: string | null;

    /**
     * Release Time
     *
     * @type {Date}
     * @memberof UpdateNoticeInput
     */
    publicTime?: Date | null;

    /**
     * Withdrawal Time
     *
     * @type {Date}
     * @memberof UpdateNoticeInput
     */
    cancelTime?: Date | null;

    /**
     * @type {NoticeStatusEnum}
     * @memberof UpdateNoticeInput
     */
    status?: NoticeStatusEnum;
}
