/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysRegion } from './sys-region';
 /**
 * 
 *
 * @export
 * @interface UpdateRegionInput
 */
export interface UpdateRegionInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    id?: number;

    /**
     * Parent ID
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    pid?: number;

    /**
     * abbreviation
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    shortName?: string | null;

    /**
     * Group name
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    mergerName?: string | null;

    /**
     * Administrative code
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    code?: string | null;

    /**
     * Postal code
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    zipCode?: string | null;

    /**
     * Area code
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    cityCode?: string | null;

    /**
     * Hierarchy
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    level?: number;

    /**
     * Pinyin
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    pinYin?: string | null;

    /**
     * longitude
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    lng?: number;

    /**
     * Dimension
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    lat?: number;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UpdateRegionInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    remark?: string | null;

    /**
     * mechanismchilditem
     *
     * @type {Array<SysRegion>}
     * @memberof UpdateRegionInput
     */
    children?: Array<SysRegion> | null;

    /**
     * name
     *
     * @type {string}
     * @memberof UpdateRegionInput
     */
    name: string;
}
