/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JobCreateTypeEnum } from './job-create-type-enum';
 /**
 * 
 *
 * @export
 * @interface UpdateJobDetailInput
 */
export interface UpdateJobDetailInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateJobDetailInput
     */
    id?: number;

    /**
     * Group Name
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    groupName?: string | null;

    /**
     * Job typeFullName
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    jobType?: string | null;

    /**
     * AssemblyName
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    assemblyName?: string | null;

    /**
     * Description information
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    description?: string | null;

    /**
     * Whether to execute in parallel
     *
     * @type {boolean}
     * @memberof UpdateJobDetailInput
     */
    concurrent?: boolean;

    /**
     * Whether to scan for attribute triggers
     *
     * @type {boolean}
     * @memberof UpdateJobDetailInput
     */
    includeAnnotation?: boolean;

    /**
     * Extra data
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    properties?: string | null;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateJobDetailInput
     */
    updatedTime?: Date | null;

    /**
     * @type {JobCreateTypeEnum}
     * @memberof UpdateJobDetailInput
     */
    createType?: JobCreateTypeEnum;

    /**
     * script code
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    scriptCode?: string | null;

    /**
     * JobId
     *
     * @type {string}
     * @memberof UpdateJobDetailInput
     */
    jobId: string;
}
