/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
 /**
 * 
 *
 * @export
 * @interface UpdateSysLdapInput
 */
export interface UpdateSysLdapInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateSysLdapInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateSysLdapInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    updateUserName?: string | null;

    /**
     * soft delete
     *
     * @type {boolean}
     * @memberof UpdateSysLdapInput
     */
    isDelete?: boolean;

    /**
     * soft delete time
     *
     * @type {Date}
     * @memberof UpdateSysLdapInput
     */
    deleteTime?: Date | null;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    tenantId?: number | null;

    /**
     * Host
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    host: string;

    /**
     * port
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    port?: number;

    /**
     * User search benchmark
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    baseDn: string;

    /**
     * Bind DN(with management restrictionsUser)
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    bindDn: string;

    /**
     * Bind password(with management restrictionsUserpassword)
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    bindPass: string;

    /**
     * User filtering rules
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    authFilter: string;

    /**
     * LDAP Version
     *
     * @type {number}
     * @memberof UpdateSysLdapInput
     */
    version?: number;

    /**
     * Bind domain account field attribute value
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    bindAttrAccount: string;

    /**
     * Bind the user's EmployeeId property value
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    bindAttrEmployeeId: string;

    /**
     * Bind the Code propertyvalue
     *
     * @type {string}
     * @memberof UpdateSysLdapInput
     */
    bindAttrCode: string;

    /**
     * @type {StatusEnum}
     * @memberof UpdateSysLdapInput
     */
    status?: StatusEnum;
}
