/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Translation TableUpdateInputParameter
 *
 * @export
 * @interface UpdateSysLangTextInput
 */
export interface UpdateSysLangTextInput {

    /**
     * Primary keyId
     *
     * @type {number}
     * @memberof UpdateSysLangTextInput
     */
    id: number;

    /**
     * Name of the affiliated entity
     *
     * @type {string}
     * @memberof UpdateSysLangTextInput
     */
    entityName: string;

    /**
     * Associated Entity ID
     *
     * @type {number}
     * @memberof UpdateSysLangTextInput
     */
    entityId: number;

    /**
     * Field Name
     *
     * @type {string}
     * @memberof UpdateSysLangTextInput
     */
    fieldName: string;

    /**
     * Language code
     *
     * @type {string}
     * @memberof UpdateSysLangTextInput
     */
    langCode: string;

    /**
     * Translate content
     *
     * @type {string}
     * @memberof UpdateSysLangTextInput
     */
    content: string;
}
