/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { YesNoEnum } from './yes-no-enum';
 /**
 * 
 *
 * @export
 * @interface UpdateConfigInput
 */
export interface UpdateConfigInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateConfigInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateConfigInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateConfigInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateConfigInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateConfigInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    updateUserName?: string | null;

    /**
     * name
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    name: string;

    /**
     * Encoding
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    code?: string | null;

    /**
     * Parameter value
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    value?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof UpdateConfigInput
     */
    sysFlag?: YesNoEnum;

    /**
     * GroupEncoding
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    groupCode?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UpdateConfigInput
     */
    orderNo?: number;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateConfigInput
     */
    remark?: string | null;
}
