/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Update file storage providerInputParameter
 *
 * @export
 * @interface UpdateFileProviderInput
 */
export interface UpdateFileProviderInput {

    /**
     * storage provider
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    provider: string;

    /**
     * bucket name
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    bucketName: string;

    /**
     * Access KeyID（All cloud service providers unifiedoneUse thisField）
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    accessKey?: string | null;

    /**
     * key
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    secretKey?: string | null;

    /**
     * Region
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    region?: string | null;

    /**
     * Endpoint Address
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    endpoint?: string | null;

    /**
     * Whether to enable HTTPS
     *
     * @type {boolean}
     * @memberof UpdateFileProviderInput
     */
    isEnableHttps?: boolean | null;

    /**
     * Enable cache?
     *
     * @type {boolean}
     * @memberof UpdateFileProviderInput
     */
    isEnableCache?: boolean | null;

    /**
     * Enable or not
     *
     * @type {boolean}
     * @memberof UpdateFileProviderInput
     */
    isEnable?: boolean | null;

    /**
     * Is the default provider
     *
     * @type {boolean}
     * @memberof UpdateFileProviderInput
     */
    isDefault?: boolean | null;

    /**
     * Custom Domain
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    sinceDomain?: string | null;

    /**
     * sequence number
     *
     * @type {number}
     * @memberof UpdateFileProviderInput
     */
    orderNo?: number | null;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    remark?: string | null;

    /**
     * Supported ServicesType（JSONFormat）
     *
     * @type {string}
     * @memberof UpdateFileProviderInput
     */
    businessTypes?: string | null;

    /**
     * Priority
     *
     * @type {number}
     * @memberof UpdateFileProviderInput
     */
    priority?: number;

    /**
     * Primary keyId
     *
     * @type {number}
     * @memberof UpdateFileProviderInput
     */
    id: number;
}
