/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysUser } from './sys-user';
 /**
 * 
 *
 * @export
 * @interface UpdateOpenAccessInput
 */
export interface UpdateOpenAccessInput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UpdateOpenAccessInput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UpdateOpenAccessInput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    updateUserName?: string | null;

    /**
     * Bind Tenant Id
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    bindTenantId?: number;

    /**
     * @type {SysUser}
     * @memberof UpdateOpenAccessInput
     */
    bindUser?: SysUser;

    /**
     * Identity mark
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    accessKey: string;

    /**
     * key
     *
     * @type {string}
     * @memberof UpdateOpenAccessInput
     */
    accessSecret: string;

    /**
     * Bind user ID
     *
     * @type {number}
     * @memberof UpdateOpenAccessInput
     */
    bindUserId: number;
}
