/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountTypeEnum } from './account-type-enum';
import { CardTypeEnum } from './card-type-enum';
import { CultureLevelEnum } from './culture-level-enum';
import { GenderEnum } from './gender-enum';
import { StatusEnum } from './status-enum';
import { SysOrg } from './sys-org';
 /**
 * 
 *
 * @export
 * @interface UserOutput
 */
export interface UserOutput {

    /**
     * SnowflakeId
     *
     * @type {number}
     * @memberof UserOutput
     */
    id?: number;

    /**
     * Creation Time
     *
     * @type {Date}
     * @memberof UserOutput
     */
    createTime?: Date;

    /**
     * Update Time
     *
     * @type {Date}
     * @memberof UserOutput
     */
    updateTime?: Date | null;

    /**
     * CreatorId
     *
     * @type {number}
     * @memberof UserOutput
     */
    createUserId?: number | null;

    /**
     * Creator name
     *
     * @type {string}
     * @memberof UserOutput
     */
    createUserName?: string | null;

    /**
     * Modifier ID
     *
     * @type {number}
     * @memberof UserOutput
     */
    updateUserId?: number | null;

    /**
     * Modifier name
     *
     * @type {string}
     * @memberof UserOutput
     */
    updateUserName?: string | null;

    /**
     * Organization ID
     *
     * @type {number}
     * @memberof UserOutput
     */
    orgId?: number;

    /**
     * Tenant ID
     *
     * @type {number}
     * @memberof UserOutput
     */
    tenantId?: number | null;

    /**
     * Account number
     *
     * @type {string}
     * @memberof UserOutput
     */
    account: string;

    /**
     * Real Name
     *
     * @type {string}
     * @memberof UserOutput
     */
    realName?: string | null;

    /**
     * Nickname
     *
     * @type {string}
     * @memberof UserOutput
     */
    nickName?: string | null;

    /**
     * Avatar
     *
     * @type {string}
     * @memberof UserOutput
     */
    avatar?: string | null;

    /**
     * @type {GenderEnum}
     * @memberof UserOutput
     */
    sex?: GenderEnum;

    /**
     * age
     *
     * @type {number}
     * @memberof UserOutput
     */
    age?: number;

    /**
     * date of birth
     *
     * @type {Date}
     * @memberof UserOutput
     */
    birthday?: Date | null;

    /**
     * ethnic group
     *
     * @type {string}
     * @memberof UserOutput
     */
    nation?: string | null;

    /**
     * Mobile phone number
     *
     * @type {string}
     * @memberof UserOutput
     */
    phone?: string | null;

    /**
     * @type {CardTypeEnum}
     * @memberof UserOutput
     */
    cardType?: CardTypeEnum;

    /**
     * ID number
     *
     * @type {string}
     * @memberof UserOutput
     */
    idCardNum?: string | null;

    /**
     * Email
     *
     * @type {string}
     * @memberof UserOutput
     */
    email?: string | null;

    /**
     * address
     *
     * @type {string}
     * @memberof UserOutput
     */
    address?: string | null;

    /**
     * @type {CultureLevelEnum}
     * @memberof UserOutput
     */
    cultureLevel?: CultureLevelEnum;

    /**
     * political outlook
     *
     * @type {string}
     * @memberof UserOutput
     */
    politicalOutlook?: string | null;

    /**
     * Graduation school
     *
     * @type {string}
     * @memberof UserOutput
     */
    college?: string | null;

    /**
     * Office phone
     *
     * @type {string}
     * @memberof UserOutput
     */
    officePhone?: string | null;

    /**
     * Emergency Contact
     *
     * @type {string}
     * @memberof UserOutput
     */
    emergencyContact?: string | null;

    /**
     * Emergency contact number
     *
     * @type {string}
     * @memberof UserOutput
     */
    emergencyPhone?: string | null;

    /**
     * UrgentContact address
     *
     * @type {string}
     * @memberof UserOutput
     */
    emergencyAddress?: string | null;

    /**
     * Personal Profile
     *
     * @type {string}
     * @memberof UserOutput
     */
    introduction?: string | null;

    /**
     * Sort
     *
     * @type {number}
     * @memberof UserOutput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof UserOutput
     */
    status?: StatusEnum;

    /**
     * Remarks
     *
     * @type {string}
     * @memberof UserOutput
     */
    remark?: string | null;

    /**
     * @type {AccountTypeEnum}
     * @memberof UserOutput
     */
    accountType?: AccountTypeEnum;

    /**
     * @type {SysOrg}
     * @memberof UserOutput
     */
    sysOrg?: SysOrg;

    /**
     * Direct Supervisor ID
     *
     * @type {number}
     * @memberof UserOutput
     */
    managerUserId?: number | null;

    /**
     * Job ID
     *
     * @type {number}
     * @memberof UserOutput
     */
    posId?: number;

    /**
     * Job number
     *
     * @type {string}
     * @memberof UserOutput
     */
    jobNum?: string | null;

    /**
     * Rank
     *
     * @type {string}
     * @memberof UserOutput
     */
    posLevel?: string | null;

    /**
     * Professional title
     *
     * @type {string}
     * @memberof UserOutput
     */
    posTitle?: string | null;

    /**
     * Areas of expertise
     *
     * @type {string}
     * @memberof UserOutput
     */
    expertise?: string | null;

    /**
     * Office area
     *
     * @type {string}
     * @memberof UserOutput
     */
    officeZone?: string | null;

    /**
     * Office
     *
     * @type {string}
     * @memberof UserOutput
     */
    office?: string | null;

    /**
     * Date of Joining
     *
     * @type {Date}
     * @memberof UserOutput
     */
    joinDate?: Date | null;

    /**
     * Latest login IP
     *
     * @type {string}
     * @memberof UserOutput
     */
    lastLoginIp?: string | null;

    /**
     * Latest login location
     *
     * @type {string}
     * @memberof UserOutput
     */
    lastLoginAddress?: string | null;

    /**
     * Latest login time
     *
     * @type {Date}
     * @memberof UserOutput
     */
    lastLoginTime?: Date | null;

    /**
     * Latest login devices
     *
     * @type {string}
     * @memberof UserOutput
     */
    lastLoginDevice?: string | null;

    /**
     * Electronic signature
     *
     * @type {string}
     * @memberof UserOutput
     */
    signature?: string | null;

    /**
     * Language code（such as zh-CN）
     *
     * @type {string}
     * @memberof UserOutput
     */
    langCode?: string | null;

    /**
     * Personalized homepage address
     *
     * @type {string}
     * @memberof UserOutput
     */
    homepage?: string | null;

    /**
     * Organization name
     *
     * @type {string}
     * @memberof UserOutput
     */
    orgName?: string | null;

    /**
     * Job title
     *
     * @type {string}
     * @memberof UserOutput
     */
    posName?: string | null;

    /**
     * Character namecall
     *
     * @type {string}
     * @memberof UserOutput
     */
    roleName?: string | null;

    /**
     * DomainUser
     *
     * @type {string}
     * @memberof UserOutput
     */
    domainAccount?: string | null;
}
