/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET General Permission Development Platform
 * let .NET Develop more simply、More general、More popular。wholeIn line with the latest technology，Modular Plugin-Based Development，Frontend and backendpointsLeave，Ready to use out of the box。<br/><u><b><font color='FF0000'> 👮This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project! </font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WechatPayTransactionInput
 */
export interface WechatPayTransactionInput {

    /**
     * OpenId
     *
     * @type {string}
     * @memberof WechatPayTransactionInput
     */
    openId?: string | null;

    /**
     * Order amount
     *
     * @type {number}
     * @memberof WechatPayTransactionInput
     */
    total?: number;

    /**
     * Product description
     *
     * @type {string}
     * @memberof WechatPayTransactionInput
     */
    description?: string | null;

    /**
     * AdditionalData
     *
     * @type {string}
     * @memberof WechatPayTransactionInput
     */
    attachment?: string | null;

    /**
     * Discount Tag
     *
     * @type {string}
     * @memberof WechatPayTransactionInput
     */
    goodsTag?: string | null;

    /**
     * Business Tag，used to dividepointsWhat business do you do?
     *
     * @type {string}
     * @memberof WechatPayTransactionInput
     */
    tags?: string | null;

    /**
     * The primary key corresponding to the business
     *
     * @type {number}
     * @memberof WechatPayTransactionInput
     */
    businessId?: number;
}
