// The copyright, trademark, patent and other related rights of the Admin.NET project are protected by corresponding laws and regulations. Use of this project shall comply with relevant laws, regulations and license requirements.
//
// This project is distributed and used primarily under the MIT License and the Apache License (version 2.0). The license is located in the LICENSE-MIT and LICENSE-APACHE files in the root of the source tree.
//
// This project may not be used to engage in activities that endanger national security, disrupt social order, infringe on the legitimate rights and interests of others, and other activities prohibited by laws and regulations! We do not assume any responsibility for any legal disputes and liabilities arising from the secondary development of this project!

namespace Admin.NET.Core.Service;

public class WechatPayTransactionInput
{
    /// <summary>
    /// OpenId
    /// </summary>
    public string OpenId { get; set; }

    /// <summary>
    /// Order amount
    /// </summary>
    public int Total { get; set; }

    /// <summary>
    /// Product description
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Additional data
    /// </summary>
    public string Attachment { get; set; }

    /// <summary>
    /// Offer mark
    /// </summary>
    public string GoodsTag { get; set; }

    /// <summary>
    /// Business tags, used to distinguish what business is being done
    /// </summary>
    public string Tags { get; set; }

    /// <summary>
    /// The primary key corresponding to the business
    /// </summary>
    public long BusinessId { get; set; }
}

public class WechatPayParaInput
{
    /// <summary>
    /// OrderId
    /// </summary>
    public string PrepayId { get; set; }
}

public class WechatPayRefundDomesticInput
{
    /// <summary>
    /// Business No generated by the merchant
    /// </summary>
    [Required]
    public string TradeId { get; set; }

    /// <summary>
    /// Reason for refund
    /// </summary>
    public string Reason { get; set; }

    /// <summary>
    /// Refund amount
    /// </summary>
    [Required]
    public int Refund { get; set; }

    /// <summary>
    /// Original order amount
    /// </summary>
    [Required]
    public int Total { get; set; }
}

public class WechatPayPageInput : BasePageInput
{
    /// <summary>
    /// Add time range
    /// </summary>
    public List<DateTime?> CreateTimeRange { get; set; }
}